### ISSUE TITLE
jti replay cache for PrivateKeyJwtSecretValidator

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1123]

**Comment by jaanclaeys** [comment]
I need this to for compliance. It is also in the spec. I saw it was removed in IdentityServer 3 for some reason.
I implemented this some time ago on another platform, and also put a time limit on the validity of the jwt token not to have an endless cache, and make this configurable

You could consider this:
- First check if JTI is in there, otherwise reject 
- Check if validity is not more than a predefined time
- Use cache, and cache JTI for that predefined time.

> A unique identifier for the token, which can be used to prevent reuse of the token. These tokens MUST only be used once, unless conditions for reuse were negotiated between the parties; any such negotiation is beyond the scope of this specification.

**Comment by leastprivilege** [comment]
work continues here: https://github.com/IdentityServer/IdentityServer4/pull/4153
