### ISSUE TITLE
Support OAuth2 MAC token profile

### ISSUE THREAD

**Issue by tedvanderveen** [IdentityServer/IdentityServer4#113]
At the moment this repo support Bearer token profile. For additional security, will the be support for MAC token profile also? See http://tools.ietf.org/html/draft-ietf-oauth-v2-http-mac-01

**Comment by leastprivilege** [comment]
This spec is retired for a long time already (Expires: August 11, 2012)

Since the specs that are meant to replace it are not done yet - we have experimental support in idsrv3. We will port that to 4 at some point - but it is pretty low on our priority list.

https://identityserver.github.io/Documentation/docsv2/pop/overview.html
