### ISSUE TITLE
Extending the Client and Claim classes to include extra fields?

### ISSUE THREAD

**Issue by yehonathan** [IdentityServer/IdentityServer4#1162]
Hi I will like to know if there is currently a way to extend the Client and Claim classes to accommodate other fields?

**Comment by leastprivilege** [comment]
what does that mean?

**Comment by yehonathan** [comment]
I mean can i extend [this](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Models/Client.cs) to for instance include **ClientType** property?

**Comment by leastprivilege** [comment]
nothing stops your from deriving from it and returning that derived type from your client store. You would then downcast when needed.

**Comment by yehonathan** [comment]
oh yeah...i see what you mean. I am however using entity framework so. I am guessing there is more to it than that.

**Comment by brockallen** [comment]
Correct, if you need custom data beyond what we provide you can either fork and do your own, or design an ancillary DB table that has FKs to the ones we provide.

**Comment by zinov** [comment]
I am trying to extend all your classes in a different way but I don't know if I am falling in the correct path. 
Let's say that I want to mark all your classes with an interface that has only an Id that works directly with my repositories. I create a derived type and implement my interface, so far it sounds good for me. Now, if I want to generate the tables with my extra fields I need to implement a ConfigurationDbContext. Well I created my own DbContext inheriting from ConfigurationDbContext, at this point I reached 2 problems 
1- I needed to create an IEntityConfiguration for each of my classes to apply them all inside the OnModelCreate. So far the result is fine but if in my configurations I wanted to change the default schema for some reason it was not applied. It maintained the dbo.
2- If I want to apply a QueryFilter for my entities is something that is not possible because the QueryFilters of EntityFrameworkCore can only be applied on a root entity, not in a subclass

I posted the idea here on stavkoverflow: https://stackoverflow.com/questions/50499138/changing-schema-on-identityserver-when-customizing-the-configurationdbcontext

Any thoughts?

**Comment by parkinsona** [comment]
@zinov , did you ever have any success with this? I've tried your solution in stackoverflow but I get an issue when trying to run migrations.

**Comment by zinov** [comment]
@parkinsona. I ended creating my own storage and not messing around with the classes they have and I implemented the IClientStore. 

http://docs.identityserver.io/en/latest/topics/clients.html?highlight=Store

I recommend you to do it on this way and then to you tables you can apply your schema and all the Configuration you need. Don't try to extend the framework on the ways I was doing it because there are limitations as you can see.

**Comment by Rzassar** [comment]
Maybe [this](https://stackoverflow.com/a/56939189/862795) link helps.
