### ISSUE TITLE
Using IdentityServer4 as pure Secure Token Server with multiple external Authentication Providers

### ISSUE THREAD

**Issue by Sand0rf** [IdentityServer/IdentityServer4#1163]
I'm trying to create a 'pure' RP-STS where no userdata is stored within the IdentityServer and the id_token is transfered from the external authentication endpoint (Google, Facebook, Twitter and two ADFS applications (using oAuth2/OpenID Connect)). The default behaviour of IdentityServer4 is to provision the user to the local userstore when the user is not kwown. The client then requests consent from the IdentityServer to use the details of the user.

Is there a mode in which no user details are stored on the token server and the result from the request at the authentication endpoint is added to the oAuth result that the client requested from IdentityServer?

**Comment by leastprivilege** [comment]
There is no default behavior. You do whatever you want.

**Comment by TomCJones** [comment]
Actually there are always two items in the IdP that must be there that could be released once the user has authenticated.
1 the existence of the authenticated user on the IdP.
2. The identifier of the user on the IdP.
These are both user private information that should only be released on user consent.

**Comment by leastprivilege** [comment]
I think @Sand0rf wants a "pass through" mechanism - and that is totally OK - you don't need to create an account - consent is done at the "account source".

**Comment by TomCJones** [comment]
ahh, so that means IdentityServer acts more like a federation server (like adfs)? 
So the identifier is just that provided by the originating IdP as is all user consent stuff?
But in that case the IdentityServer has no user details?
Clearly the IdentityServer cannot provide user consent if it doesn't talk to the user.
Or if the user did supply attributes to the IdentityServer they were requested in a fraudulent manner?
I guess none of that makes any sense to me.

**Comment by brockallen** [comment]
>  But in that case the IdentityServer has no user details?

Correct -- you bring your users (and UI) to IdentityServer. We bring the OIDC protocol. See our sample UI to understand better how those two things communicate.
