### ISSUE TITLE
Discovery endpoint includes duplicate scopes

### ISSUE THREAD

**Issue by bungeemonkee** [IdentityServer/IdentityServer4#1164]
I have a few scope names that are re-used by multiple resources and clients. This seems to work fine with the one exception of the `.well-known/openid-configuration` endpoint. Inside the `scopes_supported` element I'm seeing those scope names repeated. It doesn't actually seem to break anything I can find so far.

I dug through the code and think there is a simple fix. In DiscoveryResponseGenerator.cs line 163
`var scopes = new List<string>();` could be changed to `var scopes = new HashSet<string>();` then each call to `AddRange` can be replaced with `UnionWith` and duplicate entries would simply be ignored. This would also work with the claims variable on line 189 if that seems prudent. I can create a PR to this effect if you agree that A) this is actually an issue and B) this is the best approach to fix it.

Thanks!

**Comment by leastprivilege** [comment]
scope names must be unique.

**Comment by bungeemonkee** [comment]
So Identity Server simply does not support multiple known resources which happen to include common scope names? Is this an Identity Server requirement or is it OAuth 2? I was unable to find anything in RFC6749 requiring this but I may have missed it. Can you point me to anything to help me understand? I don't see why a single scope name can't provide access to functionality or information across multiple resources.

**Comment by leastprivilege** [comment]
in oauth/oidc on a protocol level you request a scope - to be able to uniquely match that to the resource you are requesting - the scope name must be unique.

**Comment by brockallen** [comment]
All set on this? Can we close?

**Comment by MonDeveloper** [comment]
I agree with both of you:
- Scope must be unique (as said by @leastprivilege and @brockallen) 
- Something to make the List unique is due (as requested by the @bungeemonkee).

I mean, the classic "vision" of the IdentityServer authors (or at least the vision I understood reading the docs) classify the "Scope" as something "smaller" that the "Api", I started designing my solution with this approach in mind but after some time I decided to flip upside-down the design giving to the Scope concept a "wider" boundaries, now in my design the Scope can include many WebApi, in this way I obtained a couple of advantages:
- no more introspection from the API to invoke another API "re-audit" the token, now the token always include all the allowed auditors and all the allowed roles
- with hundreds of API (BFF, BE, REST API) now it's easier to map technicalities with functional requirements

I know it has some drawbacks but it works pretty good for us, I'm not saying this is a better design but doing my way, the discovery endpoint duplicate dozen of times the scopes, and this is incorrect because those scopes are the same, just referred by many WebApi.

Do you think I have to open a new Issue?
