### ISSUE TITLE
Audience value set incorrectly?

### ISSUE THREAD

**Issue by obosha** [IdentityServer/IdentityServer4#127]
In "DefaultTokenService.cs", it has a CreateAccessTokenAsync method.

It assigns to the audience value:
Audience = string.Format(Constants.AccessTokenAudience, **issuer**.EnsureTrailingSlash())

But the issuer shouldn't be assigned to a token's audience value as far as I'm aware.  The audience should be set to who the token is intended for (the resource or relying party).

Or am I mistaken?

**Comment by obosha** [comment]
So correct me if I'm wrong, but this sounds like a "convention" that you decided upon for IdentityServer, that does not follow the typical use of "audience"?

I see in your "UseIdentityServerAuthenticationMiddleware" that you have "ValidateAudience" hard coded to false as well (TokenValidationParameters), so basically you're suggesting that audience validation is not needed (perhaps implying scopes are what should be used instead)?

**Comment by brockallen** [comment]
Audience is a JWT concept, scope is an OIDC/OAuth2 concept and they both have overlapping semantics. Our approach is a tradeoff, also given some of the other constraints we have (e.g. IIRC the Microsoft JWT handler didn't allow multiple audiences).

As I said above, scope is what you should use to audience checking, since it's providing the same feature (in conjunction with the correct authority).

**Comment by obosha** [comment]
Yup, makes sense!  I just wanted to make sure we were on the same page.

Thanks Brock.  And also...  thanks for the great work on IdentityServer4 and getting it ported to Core.  Absolutely loving Core and excited for what this is going to offer to .NET developers.
