### ISSUE TITLE
Why should I ever get Clients from database?

### ISSUE THREAD

**Issue by BoasE** [IdentityServer/IdentityServer4#1307]
I'm currently implementing the IdentityServer for a portal. This works pretty fine, but I wonder why should i ever want to read the client config from a database.

Isn't it a security risk by design if the allowed clients could be changed by a database? also the clients aren't normaly changing very much, are they?

In my case i have the clients in a inmemory repository only. is there any concerns about this? Or does some agree its better to don't have them in a changeable database?

**Comment by bharaba** [comment]
It's worse if you have them in code since they persist in source control. Having the clients and users in db allows you to create new ones and more importantly revoke existing ones without having to redeploy. If you are worried ajout securing your database, just obfuscate your db credentials and supply them during deployment.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
