### ISSUE TITLE
Identity Server Not returning the Correct Access Token

### ISSUE THREAD

**Issue by gauravawr** [IdentityServer/IdentityServer4#1332]
I am makeing a call to identity server from angular2(java script client app), but its not returning the correct access_token, instead its returning something like

b8fee3ff98859c83e69b68376b413a542217cb9f054fc9638e885fe18650f880

**Comment by leastprivilege** [comment]
not enough information.

**Comment by MovGP0** [comment]
I agree that there is not enough information. I can speculate that this might be a reference token instead of an JWT token, so you can check your configuration for that. 

For an detailed analysis, you should give an code example of your client settings and describe the HTTP-Requests + URLs from your browser log. 

(ie. in Chrome: hit `F12`, switch to `Browser Log`, enable `Preserve Log`, execute the calls, and note down the URLs from the request/response headers)
