### ISSUE TITLE
Question : Info on Default ClaimService and Profile service

### ISSUE THREAD

**Issue by akshetty9** [IdentityServer/IdentityServer4#1405]
I have been following Dominick's blog and video on identity v/s permissions. I do realize we are one of those using or trying to use it wrongly in our project. Sorry for the long write up.

We define roles and assign one or more permissions (simple string) to the roles. Roles are assigned to users. We are using authcode flow for an web application which calls other web apis, which are registered as resource servers with ids. Access token issued to the user will include all permissions under scopes, which will be used by the web app to make calls to other web apis and also drive the ui portions. Apis look for scopes in the token.

To achieve this, we planned to include permissions of the users in access token as scopes. 
Looking  at IDS4 code we see two places where we can try to do this.

1. Claim Service : Custom claim service which can override GetAccessTokenClaimsAsync method to include role to scope mapping to arrive at the allowed scopes instead of looking at AllowedScopes of client.
2. Profile service : Assuming the "role" is kind of user's profile data, can profile service provide this list of scopes to inferred from user role to claim service??

Any suggestions?

**Comment by nixa333** [comment]
Few days ago we had the same issue and was looking for a solution. One additional note/issue here is that the role can be changed in runtime(eg. Account admin changes role for one of the other account members, while that person is signed in and actively working with the app), and how to handle that, since it would require access token to be reissued with different set of permissions/scopes based on the newly added role.

We decided to do Resource based(Permission based) authorization on the API itself(to centralize permission check. You could do a separate service for that, but it could introduce a new bottleneck to the system).

We did as described here [http://benjamincollins.com/blog/a-working-example-of-permissions-authorization/](http://benjamincollins.com/blog/a-working-example-of-permissions-authorization/).
So essentially you make a filter attribute that checks permissions of the current user.

Looking at this section of code:

`user = await _userManager.GetUserAsync(context.User);` 
`var currentUserPermissions = await _userManager.GetUserPermissionsAsync(user);` 
           `var authorized = requirement.RequiredPermissions.AsParallel().All(rp => currentUserPermissions.Contains(rp));`
            `if (authorized) context.Succeed(requirement);` 

it would probably be smart to fetch this from some sort of cached resource, and not the database, since it's done on every request.

When you think about your case, it can definitely be done with scopes, and claim-based authorization, but that's not what scopes/claims are for, and that couldn't support changeability of the roles.
In our case we've defined a Client for MVC app through which User gets signed in, and that client has a scope that allows it to access certain parts of the API; then on the API itself, we do Permission authorization as described above.
When you have a complex permission based authorization you have to adjust things to fit your use case the best, instead of blindly following Microsoft prescribed ways.

If you would still like doing it the way you suggested, then it would probably be the best to implement IProfileService interface and method **GetProfileDataAsync**:

`public async Task GetProfileDataAsync(ProfileDataRequestContext context)` 
        ` {` 
            `var user = await _userManager.GetUserAsync(context.Subject);`
`var permissions = Get permissions(user);`
            `var claims = new List<Claim>();`
` foreach(Permission p in permissions)`
            `{`
                `claims.Add(new Claim("scope", p));`
           ` }`
            `context.IssuedClaims.AddRange(claims);`
        ` }`

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
