### ISSUE TITLE
Logo or Logout

### ISSUE THREAD

**Issue by fileman** [IdentityServer/IdentityServer4#1425]
Is right "Logo" ?
https://github.com/IdentityServer/IdentityServer4/blob/a984fc7b3ad32a17a0430fdeadf0b11deb8644cf/src/IdentityServer4/Models/Client.cs#L64

**Comment by StefanKert** [comment]
Hey there,

don´t know if we should keep up the work in different branches since I managed to get most of it working, but to answer your question:

LogoutUri got renamed to FrontChannelLogoutUri 
https://github.com/IdentityServer/IdentityServer4/blob/a984fc7b3ad32a17a0430fdeadf0b11deb8644cf/src/IdentityServer4/Models/Client.cs#L121

**Comment by fileman** [comment]
ok, thanks ... another breaking change to add at list.
