### ISSUE TITLE
Enable extensibility or replacement of endpoint route names for UI controllers

### ISSUE THREAD

**Issue by Lutando** [IdentityServer/IdentityServer4#146]
Not to be put into the same pool as [this issue](https://github.com/IdentityServer/IdentityServer4/issues/43) But It would be nice if it would be possible to specify the route names of the controllers that handle the browser interactions between the user and the identity provider. (Login/Logout/Consent/Error) That enables.

eg: change the default route of the login controller to use "/account/login" instead of "ui/login" 

A naive solution that guarantees a good developer experience doesn't pop into my mind, besides enabling developers to override these default values and making sure that you have controllers with the correct route suffix to handle the interactions.

**Comment by Carl-Hugo** [comment]
I tend to agree that it would be a good idea to allow customization.

This could easily be done by removing the route pattern of the HttpGet/HttpPost attributes from the controllers. Since an attribute need constants they cannot be used with customization in mind (well adding custom Get/Post attributes could solve that problem). More on that, it would also help achieve a greater separation of concerns (routes are routes and controllers are controllers).

This would lead to URL like "/login", "/logout" and so on.

Finally, to still use the "ui/" pattern, a developer could add a custom route pattern similar to `ui/{controller}/{action=Index}/{id?}` to MVC routing middleware (im not too sure how to do that in asp.net core, but im pretty sure it is simple). Same thing goes for "account/" or any other URL patterns that a developer want.

On another note, as my first post on GitHub, i'd also like to point out that I am pretty happy to see this project ported to .net core, good job :)

**Comment by brockallen** [comment]
Yes, this area is still very much being thought out.

**Comment by ajtowf** [comment]
Isn't this done? It's now possible to set custom routes:

    services.AddIdentityServer(options =>
    {                
        options.UserInteractionOptions.LoginUrl = "whatever";
        options.UserInteractionOptions.LogoutUrl = "whatever2";
        options.UserInteractionOptions.ConsentUrl = "whatever3";
        options.UserInteractionOptions.ErrorUrl = "whatever4";
    });

**Comment by brockallen** [comment]
Much like this: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Host/Startup.cs#L41
