### ISSUE TITLE
suggestions for documentation

### ISSUE THREAD

**Issue by Triwaters** [IdentityServer/IdentityServer4#1613]
Apologies if this is not a good place to drop this suggestion...

In the endless pursuit of perfection... in PDF page 26 (Setup and Overview) There are images with conflicting project names (QuickstartIdentityServer in one, IdentityServerQuickStart in the other),

but what may prove confusing to a complete novice (such as me) is the quickstart section that follows. It shows all three projects at a point in the documentation where the person stepping through the instructions will have (thus far) created only one. Perhaps an explanatory comment on this or, alternatively, move this section to a later spot in the document after one or both of the other projects has been created?

**Comment by MatthewGabriel** [comment]
> sheds light on where less skilled sailors will founder on the rocks
Excellent

If you have it set to **Current selection** then that just means whichever project you currently have selected is the one that will be started if you choose Debug->Start Debugging or Debug->Start Without Debugging.

So ensure you select the server project first and start that.  Give it a little while to start up properly before you start the other projects.

**Comment by wstllc** [comment]
Ah, you caught that third paragraph before I removed it. I'm rather new to Visual Studio but rather than explain what I finally figured out just after posting the comment, I went back and removed it. What had held me up prior this morning's try of the good guidance (Ctrl+F5) was my assumption that I could not start a project after another had begun. Obviously (in hindsight) not true, but I only just discovered that Ctrl+F5 really does allow me to start projects in succession. I decided this problem was far more related to my ignorance than to the document. :)
