### ISSUE TITLE
Client doesn't care about certificate change

### ISSUE THREAD

**Issue by Dev123213** [IdentityServer/IdentityServer4#1635]
I am confused how clients authenticate tokens. I will explain my setup, how I thought it worked and then my current issue.

I have Identity Server as one website and a client mvc application as a seperate app. The client is defined with HybridAndClientCredentials, AllowOfflineAccess and AccessTokenType.Jwt. It uses AddOpenIdConnect with the correct client configuration and SignInSchema = Cookies. Identity Server uses windows authentication (automatic - true, forward client cert = true) and uses a certificate from the certificate store to do it's magic. The clients, app resources and API definitions are all in a database.

How I thought it worked: The two applications load up, once the mvc app has loaded it requests a public key from identity server. On first user authentication request fail, you are redirected to identity server. IS  creates your token goodness once you log in, using the certificate it is provided in .AddSigningCredential. Finally you are redirected back to the mvc app. For the lifetime of the token, when you do any request requiring authentication, the MVC app will use the public key it grabbed from Identity Server and check the signature is valid. If so, you can continue and any claims information inside the cookie can be considered correct.

Now, I wanted to test what happens if I didn't use AddValidationKey to let clients know old tokens using the previous certificate signature are still valid. I assumed either the client app would bomb out saying invalid token, or hopefully, it would get destroyed and automatically redirected to IS login.

I cleared my cookies, set Identity Server to use the "IIS Express Development Certificate" certificate and started up the apps. I then went onto the mvc app, got redirected to IS, logged in and returned authenticated. I kept that tab open with the cookie in the chrome resources tab visible. I now stopped my apps, changed AddSigningCredential to now use the "DEV" certificate I created and started the applications again. I don't get sent to IS and the mvc app seems to be quite happy with my old cookies... is this right? I have both tabs's chrome resource tabs open to double check it is definitely the same cookie and it is.

**Comment by mclark1129** [comment]
Once you log into the MVC app, you will be authenticated with that app until the cookie expires.  AFAIK, MVC doesn't use Identity Server configuration settings to validate its cookies.  It only validates the tokens during the initial sign-in process from Identity Server.  This means that if you make any sort of Identity Server configuration changes they will not be detected by the application until the cookie expires and the user is sent through the sign-in process again.

**Comment by Dev123213** [comment]
Then how does it know the token is actually signed correctly?

**Comment by Dev123213** [comment]
In a less brief response - If the mvc app doesnt grab the public key from Identity Server to validate the cookie, how does it validate it?

**Comment by mclark1129** [comment]
It's been awhile since I deployed my implementation of IdSrv4, so maybe @leastprivilege or @brockallen can confirm or deny my understanding below:

MVC validates its cookies the same way it would whether or not you are using Identity Server, which I believe by default is using the DPAPI.  Cookie validation is a completely separate process from token validation.  Token validation DOES use the IdSrv public key, but only during the initial sign in process.  Once MVC validates the token and authenticates the user, the app makes the assumption that it does not need to keep checking whether the original token signature is valid.  In most cases that would be a huge waste of time.

However one thing to keep in mind when you're changing certificates is that you may invalidate the access token for use with downstream APIs.  Unlike client apps, APIs will frequently fetch the latest public key info from IdSrv to validate the access token it's being provided.  So if a client app was providing a token signed CertA and IdSrv was updated to use CertB, it's quite likely that downstream APIs would quickly start rejecting any tokens signed with CertA.

**Comment by leastprivilege** [comment]
The client loads the discovery document and key information at startup time - and refreshes it every 24h (by default). At least that is the behavior of the Microsoft MVC client lib.
