### ISSUE TITLE
Claim in sample project not showing in User.Claims

### ISSUE THREAD

**Issue by egmfrs** [IdentityServer/IdentityServer4#1657]
In the sample project for [Hybrid and API Access](https://github.com/IdentityServer/IdentityServer4/blob/release/docs/quickstarts/5_hybrid_and_api_access.rst)

The Users have claims for "website", however when I run the project, website does not show up in the claims list. What is missing?

**Comment by nicbavetta** [comment]
@egmfrs Have you made any progress with this?

**Comment by egmfrs** [comment]
@nicbavetta nope

**Comment by brockallen** [comment]
It's because Microsoft does not map all claims by default from the userinfo into the claims principal. You have to say what claims you want included. Here's what they include by default:

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L63

It's unfortunate that they don't map what comes back from userinfo automatically. Also unfortunate that they're missing 2/3 of the standard claim types.

// @tratcher

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
