### ISSUE TITLE
Enable authorize/token validation pipeline extensibility

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#166]
evolution of is3 custom request validators
"PreAuthenticate" regardless of logged in status

etc.

**Comment by brockallen** [comment]
Do we want to allow a redirect on the `AuthorizeRequestValidationResult` so custom implementations can send the user to a custom page?

**Comment by brockallen** [comment]
I think we need to define what the requirements are for this. Pre-authenticate used to allow both: 1) partial logins/redirects for custom UI workflows, and 2) short-circuit the login process and decide the authentication outcome prior to the login UI being displayed. I'm guessing the requirement is that we want both of these, but I think those are two different features given where each needs to fit into the authorization endpoint pipeline.

Currently there's extensibility via a custom authorization request validator. I don't think we want to allow custom redirects on the `AuthorizeRequestValidationResult` -- that should be simple protocol validation with a result of error or "continue with authorization" (especially since it's also used from the user interaction service). In short, it should only validate the param values and not try to affect workflow. So the current extensibility point doesn't feel like the right place.

For custom redirects/UI workflow, this needs to be done after the user has successfully authenticated. This extensibility should be added into the `IAuthorizeInteractionResponseGenerator`. Right now the default implementation does 2-steps of checking: 1) login related checks (prompt=login, etc), and 2) consent related checks. So if we want to allow custom redirects, I think we design it around the fact that the user has authenticated and that we've done all of our default login related checks (meaning IdentityServer doesn't think it needs to send the user to the login page). We then add custom call before we do our consent checks and we allow the custom code to do a redirect to a custom page... IOW, this is like the partial login feature from IdSvr3. After the user is done on the custom page and come back to the authorization endpoint, we'd then do all the same workflow and then the custom code would not redirect, and then the consent checks run. I think customers will want this to be a user-focused thing (EULA, etc.), thus the need to put it in between login interaction checks and consent interaction checks.

If we want to allow a hook for choosing the identity of the user from some other source other than the cookie, then we'd need to do that earlier in the authorization endpoint prior to the basic protocol validation via the authorize request validator. 

@leastprivilege did you have another use case in mind, since you mentioned pre-authenticate? So you'd want a check before the login check to allow custom code to redirect? Or are you thinking more pre-authenticate to choose the identity of the user from something other than the cookie? Or are you thinking pre-authenticate to decide the outcome of authorization without any prompt of the user (login or consent)?

**Comment by brockallen** [comment]
Having done some more thinking, I believe we already have all the extensibility points we need to handle most of the above requirements.

There's the `ICustomAuthorizeRequestValidator` that can reject any invalid combination of protocol params (including things like this user can't use that client) but this extensibility point can only produce an error result (and thus the error UI).

There's also the `IAuthorizeInteractionResponseGenerator` which wasn't always designed to be replaced, but it can be. Now, replacing would lose a lot of our built-in functionality, so I'd propose to make the default `AuthorizeInteractionResponseGenerator` public and open the methods to be `protected virtual` so that derived classes can reuse our main implementation and then surround it with their own logic (either as pre- or post-processing). Also, I'd propose we make the `ProcessLoginAsync` and `ProcessConsentAsync` also `protected virtual` so a custom implementation can put any logic in between those two steps I described above.

The only last requirement that this doesn't handle is "PreAuthenticate regardless of logged in status", and that's the one I think I want examples of use cases so we understand the requirement.

**Comment by maganuk** [comment]
When IdSrv4 was in beta, there was no east way to redirect users to the correct login page. Brock had suggested that the login page needs to change itself based on where the user was coming from. I had three applications which were using the same user database. Users access to the three apps from the backend. What I did to separate out the login pages was as follows:

    public class CustomViewLocationExpander : IViewLocationExpander
    {
        public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
        {
            string querystring = context.ActionContext.HttpContext.Request.QueryString.Value;
            if (querystring.Length == 0 || !querystring.ToLower().Contains("client_id"))
            {
                yield return "~/ui/{1}/{0}.cshtml";
                yield return "~/ui/SharedViews/{0}.cshtml";
            }
            else
            {
                var st = HttpUtility.UrlDecode(querystring).ToString().ToLower();
                string clientid = "";
                int pFrom = st.IndexOf("client_id=") + "client_id=".Length;
                st = st.Substring(pFrom, st.Length - pFrom);
                int pTo = st.IndexOf("&");
                if (pTo < 0)
                    pTo = st.IndexOf("?");
                if (pTo < 0)
                    clientid = st;                    
                else
                    clientid = st.Substring(0, pTo).ToString();
                if (clientid.Length > 0)
                {
                    yield return $"~/ui/{clientid}/{{1}}/{{0}}.cshtml";
                    yield return $"~/ui/{clientid}/SharedViews/{{0}}.cshtml";
                }
                else
                {
                    yield return "~/ui/{1}/{0}.cshtml";
                    yield return "~/ui/SharedViews/{0}.cshtml";
                }
            }
        }
    }

To be honest, I am not a big fan of this code. It could prove to be unreliable. It also means that I need to pass around the client_id and returnUrl to all sub pages (change password, confirm email, etc). 

I don't know if there is a better way of doing this with RC2. If it could be as simple as specifying the login page when setting up the clients, it would've been nice. 

For role checks during a silent renew (in case things have changed), I have extended the Models.Client to include a list of "LoginRoles".

With the CustomAuthorizeRequestValidator I'm doing the following:

        public class CustomAuthorizeRequestValidator : ICustomAuthorizeRequestValidator
        {
            private readonly MySettings _mySettings;
            private readonly IUser _service;

            public CustomAuthorizeRequestValidator(IOptions<MySettings> mySettings, IUser userService)
            {
                _mySettings = mySettings.Value;
                _service = userService;
            }

            public async Task<AuthorizeRequestValidationResult> ValidateAsync(ValidatedAuthorizeRequest request)
            {
                if (!string.IsNullOrWhiteSpace(request.ClientId) && request.Subject.Identity.IsAuthenticated == false)
                     return await Valid(request);
                else
                {
                    var allowedRoles = Clients.GetByID(_mySettings, request.ClientId).LoginRole;
                    if (await _service.CheckForRoles(request.Subject.Identity.Name, allowedRoles))
                        return await Valid(request);
                else
                    return await Invalid(request, OidcConstants.AuthorizeErrors.LoginRequired);
                }
            }

            private Task<AuthorizeRequestValidationResult> Invalid(ValidatedAuthorizeRequest request, string error = OidcConstants.AuthorizeErrors.InvalidRequest)
            {
                var result = new AuthorizeRequestValidationResult
                {
                    IsError = true,
                    Error = error,
                    ValidatedRequest = request
                };

                return Task.FromResult(result);
            }

            private Task<AuthorizeRequestValidationResult> Valid(ValidatedAuthorizeRequest request)
            {
                var result = new AuthorizeRequestValidationResult
                {
                    IsError = false,
                    ValidatedRequest = request
                };

                return Task.FromResult(result);
            }
        }

**Comment by maganuk** [comment]
I also remembered, I couldn't find a way to redirect the user to the login page when I was doing a role check in the CustomAuthorizeRequestValidator method. The user is automatically sent to the error page, after I do 

`                return await Invalid(request, OidcConstants.AuthorizeErrors.LoginRequired);
`

**Comment by brockallen** [comment]
> To be honest, I am not a big fan of this code.

I'm not either, but when I have customers that want to do this I try to discourage them. If IdentityServer is meant to be a SSO platform, then the users aren't logging into an individual client -- they're logging into your company's "suite of applications". The business/marketing people don't get this unless you explain it to them. Think about google -- you never log just into gmail -- you're logging into google and from that you have access to youtube, calendar, gmail, etc. I also think this is disingenuous to the user. 

But yea, if you must brand the login page for each client then multiple razor views is one way, or have one that's more dynamic. I don't have a better suggestion either.

**Comment by brockallen** [comment]
done

**Comment by automatonic** [comment]
I note that `AuthorizeInteractionResponseGenerator` has made `ProcessInteractionAsync` `public virtual`, but `ProcessConsentAsync` and `ProcessLoginAsync` are `protected internal virtual` as of RC3. 

Based on:

>  I'd propose we make the ProcessLoginAsync and ProcessConsentAsync also protected virtual so a custom implementation can put any logic in between those two steps I described above.

I would have expected them to be `protected virtual` and not `protected internal virtual`.

Obviously I can just implement the interface myself, but was this intentional?

**Comment by brockallen** [comment]
`protected internal virtual`

protected and internal together is an "or", not an "and"

**Comment by automatonic** [comment]
TIL: [what protected internal actually means, and not what i assumed it did](http://haacked.com/archive/2007/10/29/what-does-protected-internal-mean.aspx/). Thanks!

**Comment by automatonic** [comment]
Also, in my *over-reliance on visual studio intellisense*, I did try to type `protected override` and got no suggestions. I then assumed that was due to the desired methods being `protected internal`. Interestingly, if you instead type `protected internal`, Visual Studio *will* suggest the correct methods. After selecting one in a derived type, it then scrubs the `internal` portion. The more you know. 

Thanks for taking the time to educate me, @brockallen !
