### ISSUE TITLE
SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired.

### ISSUE THREAD

**Issue by dicksonkimeu** [IdentityServer/IdentityServer4#1689]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

Deployed OpenId, log in successful but on re direct i get this error.,

### Relevant parts of the log file

```
An unhandled exception occurred while processing the request.

SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired.
ValidTo: '11/01/2017 14:28:42'
Current time: '11/01/2017 14:34:45'.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()

Stack Query Cookies Headers
SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: '11/01/2017 14:28:42' Current time: '11/01/2017 14:34:45'.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```

**Comment by brockallen** [comment]
Sounds like some clock is not in sync.

**Comment by yosbeleg89** [comment]
@brockallen  I have the same issue: `IDX10223: Lifetime validation failed. The token is expired. ValidTo: '03/31/2018 21:49:56', Current time: '04/10/2018 14:48:43'.` Both the IdentityServer and the client are in azure hosted. This is happening after we updated to the latest IdentityModel and Microsoft.Owin.Security.OpenIdConnect packages in the client.

**Comment by yomer** [comment]
@brockallen I too have the same issue using Postman **(While debugging locally)** as @yosbeleg89 with token expiration. It can't be clock skew because the ValidTo: is always set to the same date/time. I have restarted both the IdentityServer and my debugging app, and even cleared the cookies and token on Postman. 

After getting the new Access Token in postman, I check in jwt.io and I have the expiration set at 1 hour from now.  When I try to send a request via Postman, I get the IDX10223 validation failed event: `The token is expired. ValidTo: '03/16/2019 05:51:23', Current time: '03/17/2019 17:51:28'.`

I'm using the IdentityServer DBStore for client configuration. Here's my relevant configuration for the token for this client:
![image](https://user-images.githubusercontent.com/1246242/54495837-50951380-48ad-11e9-8f5d-bed66e988464.png)

And here's the expiration on the token, taken from jwt.io:
![image](https://user-images.githubusercontent.com/1246242/54495852-79b5a400-48ad-11e9-8672-bd52ab38b7bd.png)

I have tried two different Startup configurations:

First(This one works on the production server, but not locally):
![image](https://user-images.githubusercontent.com/1246242/54495899-26902100-48ae-11e9-8026-142c2df13c5c.png)

Second(I haven't tested this on the production server, but it doesn't work locally which is what I'm trying to fix)
![image](https://user-images.githubusercontent.com/1246242/54495878-e6c93980-48ad-11e9-8ff5-38df30a19a57.png)

I'm not setting a fixed expiration date anywhere on the DBStore or on the IdentityServer startup configuration. The strange thing is that every now and then, the expiration date changes, but it always stays behind. I don't know where the ValidTo: time is coming from. As you can see it's a full day behind from what's shown in my access token from jwt.io

**Comment by joshuansu0897** [comment]
@yosbeleg89 How did you solve the problem?

i have the same issue:
```
Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed.
The token is expired. ValidTo: '07/19/2019 01:18:42', Current time: '07/23/2019 18:47:47'.
```

**Comment by yosbeleg89** [comment]
I just handled the error on the client and throw the challenge again when it happens.
