### ISSUE TITLE
Add virtuals to default IUserSession

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1791]

**Comment by lacroixdavid1** [comment]
In my opinion, it  should also all additional services listed on https://identityserver4.readthedocs.io/en/release/topics/startup.html

I'm actually forced to override `IProfileService` and rewrite whole `DefaultProfileService` logic instead of simply beeing able to override `DefaultProfileService` and calling base methods.

**Comment by lacroixdavid1** [comment]
Just made a PR #1798

**Comment by brockallen** [comment]
Done

**Comment by maganuk** [comment]
@brockallen Can I use this to set the domain on the session cookie?
