### ISSUE TITLE
Extension Grant and ASP.NET Identity

### ISSUE THREAD

**Issue by batdanilo** [IdentityServer/IdentityServer4#1899]
Hi, someone know if .AddExtensionGrantValidator<MyCustomExtensionsGrantValidator>() and .AddAspNetIdentity<IdentityExpressUser>() are compatible? I configured my identity server like this:

 services.AddIdentityServer()
            .AddTemporarySigningCredential()
            .AddOperationalStore(identityServerBuilder)
            .AddConfigurationStore(identityServerBuilder)
            .AddExtensionGrantValidator<MyCustomExtensionsGrantValidator>() 
            .AddAspNetIdentity<IdentityExpressUser>();
            ;

but, when i call my custom grant validator, always get error 500 because UserClaimsPrincipalFactory cannot create the user (ArgumentNullException: Value cannot be null. - Parameter name: user)
Please, some one know something?

**Comment by SamuelMcAravey** [comment]
I just ran into this myself. I was trying out the example in the documentation for extension grants here:
http://docs.identityserver.io/en/release/topics/extension_grants.html

So far I have found that if I didn't stick a real subject in the constructor for `GrantValidationResult` then I saw the exception you mentioned. From what happened to me it seems that I cannot use something like a client_credentials grant since I can't pull a `sub` claim from it. The moment I hard-coded an id from the `AspNetUsers` table it succeeded.

i.e.
`new GrantValidationResult("d01fad29-b4d4-4417-883d-43d2872fca93", "delegation")`

**Comment by leastprivilege** [comment]
Yes - you are supposed to return either no sub - or one that exists.

Otherwise the standard profile services will error - you can of course replace the profile service as well.

@batdanilo are you saying you are not returning a sub - and still see the error? Like here:

https://github.com/IdentityServer/IdentityServer4/blob/dev/test/IdentityServer.IntegrationTests/Clients/Setup/NoSubjectExtensionGrantValidator.cs

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by batdanilo** [comment]
Yes @brockallen you can close. Thank's to @SamuelMcAravey  and @brockallen
