### ISSUE TITLE
Add support for specifying ssl protocol UseIdentityServerAuthentication

### ISSUE THREAD

**Issue by Exocomp** [IdentityServer/IdentityServer4#1914]
I would like to be able to specify the SSL Protocol to be used with UseIdentityServerAuthentication, for example like TLS11,TLS12, etc.  I don't see an option for it currently.

```
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
{
	Authority = appSettings.Value.Authority,
	RequireHttpsMetadata = true,
	AllowedScopes =
	{
		"projectxyz.finance.api1.read_only",
		"projectxyz.finance.api1.full_access",
	}
});
```

**Comment by leastprivilege** [comment]
That would be a server setting. Check the Microsoft docs / issue tracker.

**Comment by stt106** [comment]
On a related issue, why in VS2017, it says **"'IApplicationBuilder' does not contain a definition for 'UseIdentityServerAuthentication' and no extension method 'UseIdentityServerAuthentication' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)"**
I do have **IdentityServer4.AccessTokenValidation version 2.2** nuget package (the latest) installed.

**Comment by leastprivilege** [comment]
How is that related?

That's not how you wire up handlers anymore in ASP.NET Core 2. Check the docs.

**Comment by stt106** [comment]
Sorry! Was following some old online resource and got confused...

I am trying to authenticate users from a sql db; but I am using Dapper instead of EF. As far as I know, I need to implement IResourceOwnerPaswordValidator and IProfileService, both of which use a repository interface that encapsualtes the Dapper/db connection.
Then register both with IdentityServer:
```
services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                //.AddInMemoryPersistedGrants()
                .AddInMemoryApiResources(GetApiResources())
                .AddInMemoryIdentityResources(GetIdentityResources())
                .AddInMemoryClients(GetClients(new[] { "http://localhost:4200" }))
                //.AddTestUsers(GetTestUsers())
                .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>()
                .AddProfileService<ProfileService>();
```
Everything should be the same as using in memory testing users?
But unsure why the validation logic doesn't call my ResourceOwerPasswordValidator at all.Feel like it's wried properly with IdentityServer.
Do you have any quick advice? I can post a new issue with more sample code if needed.
Thanks!
