### ISSUE TITLE
Consider removing ~/resources audience from access tokens

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1961]
and add flag to add it back in for legacy scenarios

**Comment by leastprivilege** [comment]
but userinfo needs it...

**Comment by brockallen** [comment]
> but userinfo needs it...

but we know the issuer

**Comment by richardlawidjaja** [comment]
yes please, so i was in a middle of migrating from spring framwork Oauth2 to IS4 (java to .net)
in the spring framework version looks like they have remove all the Nbf,Aud, iss etc
but i could not find a setting to hide those value, could you please consider this?

thank  you!

**Comment by dammejed** [comment]
I stumbled on this issue after wondering why this audience was on my client_credentials token all the time.
It got me curious, so if it's not much trouble to answer: in what scenarios is this audience useful?

Feel free to direct me to some documentation if this should be obvious.

**Comment by brockallen** [comment]
It's a legacy/migration feature from IdentityServer3.

**Comment by dammejed** [comment]
I gather that it's superfluous for a from-scratch deployment using IdentityServer4, then?
If so, 👍

**Comment by brockallen** [comment]
yea, in short you can ignore it

**Comment by TomCJones** [comment]
You only use the aud(ience) when your OP is creating an ID Token that is targeted to a particular audience, like, for example, one particular client.

**Comment by dammejed** [comment]
Sure, I know what the aud value in the token is for.
But this particular audience (`~/resources`) seems to be included in all tokens, despite what scope I request from the auth server-- It's why I was lead to this issue. If it's a holdover from older implementations, I'm satisfied.

**Comment by tspringr** [comment]
@brockallen 

I would like IdSrv4 to omit this audience, too. Even more than that - I'm investigating which changes are needed to accomplish this [here](https://github.com/tspringr/IdentityServer4/commit/d83f66c3e3473409386d2265d028f88cc29bb8b7)

Just to double-check: Are you sure it's necessary to introduce the flag and extra conditional statements in order to remain backwards-compatible in this case. As you said before, the /userinfo endpoint can validate the issuer and who else would expect this audience to be present? 

The reason I'm asking is, just in general, I would prefer to avoid these extra conditionals whenever possible to keep the code simpler/cleaner.

Thank you

**Comment by muziekklas** [comment]
@brockallen @leastprivilege  What is the status on this? We use a Progress Backend using plugins which cannot parse a string[],  but even after playing with thre requested scopes, the token keeps giving two aud values. Is there a way we can disable the /resource audience? Or can you give a hint how we could avoid this? 
Thanks in advance!! :)

**Comment by frenklin** [comment]
Could somebody merge @tspringr changes? I don't want to sign CLA so even can't create merge request.

**Comment by leastprivilege** [comment]
OK. Done for 3.0
