### ISSUE TITLE
Add forgot password/reset password workflow for ASP.NET sample UI

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1970]
We would like a UI for a forgot password/reset password workflow and it would need to be in a separate feature folder different from the "Account" (or any of the others).

If you're interesting in helping/contributing this feature, please contact us first.

**Comment by navidehsa** [comment]
I am trying to implement reset password , I am not sure how to create callbackurl which should be send by email??would please help me on that?

**Comment by mhtsbt** [comment]
Hi, I would like to contribute some of the requested samples. As I am going to need them myself. 

If I read correctly they would have to be comitted to: IdentityServer4.AspNetIdentity/src/Host/Quickstart/ in seperate feature folders

**Comment by brockallen** [comment]
@mhtsbt Actually, elsewhere: https://github.com/IdentityServer/IdentityServer4/issues/1971#issuecomment-356751798

**Comment by CarlosTorrecillas** [comment]
Hi guys, is there any kind of sample I could look at? I’d like to add that feature to my existing workflow and just saw this.

Thanks!

**Comment by TomCJones** [comment]
Just build an asp app in vs selecting indivual autn. It only takes 5mins to get running.

**Comment by benosman** [comment]
@TomCJones - I understand how to build a reset password system, either using Identity or homegrown.

It would be created on the Identity server itself, but how does one handle redirecting back to the relevant client?

For instance:
1. Visit 'Client App 1'
2. Click login link, or try to access protected content
3. Redirect to Identity server login page for that app. 
4. Click forgot password link, email gets sent
5. Click link inside email, set new password on Identity server
6. Automatically login the user to identity server, no need to login with new password
7. Since the user is now at the identity server, how can we find out the url for the relevant Client App, and is there a way to complete the originally intended login there without multiple redirects?

**Comment by brockallen** [comment]
> It would be created on the Identity server itself, but how does one handle redirecting back to the relevant client?

I think that's really hard to do. Resetting a password (via email) is async and could take time. The client most likely has timed out waiting for the OIDC response. In short, I never bother to do what you're wanting to do.

**Comment by benosman** [comment]
@brockallen 
I wondered if something like that would be the case, as I couldn't think of an obvious solution to it.

Since, I have one primary client, and just a few secondary clients, so I might just keep track of the client name in the reset url, and then do a redirect from the controller to a protected page on the relevant site to re-initiate a sign in process.

**Comment by brockallen** [comment]
Sure, if you have one main place you could send the user once that workflow is done, then send them there. That it better than nothing.

**Comment by TomCJones** [comment]
You should be able to send them to a page that automatically initiates a login. You can also store the most recent client they visited in the user record, which should be where the last logon attempt occurred.

**Comment by leastprivilege** [comment]
We decided that we will not provide/maintain a UI based on ASP.NET Identity that supports the full account management lifecycle.

**Comment by benosman** [comment]
@julianwesleyan - yes, that's pretty much the approach we went for in the end.

**Comment by julianwesleyan** [comment]
@benosman - awesome that's what I'm doing now.

**Comment by davidayalagt** [comment]
Hey @benosman or @julianwesleyan do you have any public repo or could you share a sample of what you're doing, I'm about to start this process, any help is much appreciated.
