### ISSUE TITLE
Investigate user authentication using X.509 certificates

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#214]

**Comment by leastprivilege** [comment]
That will be the job of the account controller or a custom grant validator. Will be more a sample than a IS feature.

**Comment by leastprivilege** [comment]
Waiting for @blowdart

**Comment by leastprivilege** [comment]
waiting for https://github.com/blowdart/idunno.Authentication/issues/11

**Comment by martindlarsson** [comment]
Just curious, is there no way of authenticating user with client certificates right now with IS4?

I am working on securing a couple of API (ASP.Net Core) endpoints and I need to authenticate and authorize users (users of a web portal) with client certificate. Are my users actually clients since the we portal stands in the middle? All users have individual certificates stored on their smart cards.

**Comment by leastprivilege** [comment]
We support what is supported by ASP.NET Core - right now there is nothing official.

See https://github.com/blowdart/idunno.Authentication/issues/11
