### ISSUE TITLE
Consider formal support for token exchange

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2310]
https://datatracker.ietf.org/doc/draft-ietf-oauth-token-exchange/

It can be done with the current extension grants, but if/how could it be formalized?

Sponsors welcome.

**Comment by LindaLawton** [comment]
I need to read the full spec doc.    However if the first few pages are a guide this is something that is on the books here for September.   

What we need is something like client credentials that can be used back end by a service running.   which will be granted permissions to access user on behalf of a user.    (impersonation) 

I was going to contact you guys about how best to go about this.   My current idea was to have the user that was impersonated added as a client property then hack building the claims returned.      

I will return after i have read though this document.

**Comment by LindaLawton** [comment]
>It can be done with the current extension grants

Are you sure it can be done with [extension grants](http://docs.identityserver.io/en/release/topics/extension_grants.html)?  I am not seeing how we can pass a `subject_token` beyond the user token the user already has which to me is probably going to be the `actor_token`.  IMO for it to work with `IExtensionGrantValidator ` we would need the ability to send the described parameters with the request not the standard ones.    

It looks to me like this is going to require a whole new endpoint that being /as/token.oauth2 trying to figure out why its called that in the RFC.    Not to mention that client would need the ability to store the users who its allowed to impersonate (`subject_token`).

I managed to get this added to the current sprint.

**Comment by LindaLawton** [comment]
@brockallen I realize you guys are very busy.  However I need some feed back on this.   I do not want to add this to a fork and then run a fork in production for months.  I need some information on a time frame of it being merged.    

I am wondering if it would be easier to just do this as an additional DLL which we could run along side the official version of Identity server 4.

**Comment by leastprivilege** [comment]
We will not implement this (nor spend more time with it) before the spec is finalized.

Been there. Things change last minute.

I think this can be done as an extension grant - but I haven't tried it.

**Comment by LindaLawton** [comment]
I have sent an email off to the others of the spec.   With a few questions.   I can find out what their status is.

I tried with extension grants yesterday and was unable to see how you could send the subject token to to it.  It assumes you are the user who you are logged in as.   It appears this just works if you want to use lazy delegation to another api in the system not another user.

Thanks for your response if your not interested in implementing it I don't need to spend the time adding it here.

**Comment by leastprivilege** [comment]
As I said - once the spec is final, it is more worthwhile spending cycles on it.

**Comment by brockallen** [comment]
We're trying to use the milestones here in github to assign dates/priority to issues/enhancements. "Future" means no time soon. Other milestones are sooner than "Future" :)

**Comment by chrisowhite** [comment]
I'm thinking require injecting a validator implementation that handles determining if the subject making the request is allowed to do what they're requesting (ex. can A impersonate B). Just like you're required to specify certain store implementations.

**Comment by LindaLawton** [comment]
@chrisowhite i used a custom grant type that works a bit like client_credentials but returns the token for the user being impersonated.      The only issue is that there is no way to see that A is impersonating B.  As far as the system knows its B performing the actions.

**Comment by LindaLawton** [comment]
Chris any chance you want to give me some feedback on this approach?    its in production now working fine but I like your approach as well.

https://www.daimto.com/identity-server-4-user-delegation/

**Comment by chrisowhite** [comment]
I went with my own extension of the JWT bearer spec since it specifies requesting an authorization grant on behalf of a resource owner, where client credentials does not (as you noted).

https://tools.ietf.org/html/rfc7523#section-2.1

Seems like token exchange spec isn't too far off from the way I went since it requires an existing grant to authorize (validating a JWT signature or a stored reference token).

The route you chose seems like the quicker/easier option since there is already something in place to authenticate the client. In my implementation I require client authentication and also validate the signature of the supplied JWT. We only allow the grant type for our internal clients but I implemented in a way that a certificate can be configured per-client. 

We operate a SASS application, so if IdentityServer4 were to officially support token exchange, I would want a way to inject a validator to that determine if a subject is allowed to request the access of another. Ultimately it's all about trust, so you have to trust that the client is not simply providing a subject that it knows is allowed impersonated/delegated access.

**Comment by LindaLawton** [comment]
We also operate a SASS web application.   The solution i came up with was quick and dirty because it needed to be in production now and only for an internal client.  

I like your solution as it validates the JWT and we will have a third party customer who will be using this in the fall.   Its probably best to have a more secure option when working with third parties.

**Comment by chrisowhite** [comment]
I implemented our approach in IdentityServer2, before the token exchange first draft was published. I hesitate to call it a hack since it basically adds onto the JWT bearer authorization grant spec (at the time), but I'd certainly consider it a hack now.

**Comment by amadard** [comment]
@brockallen @leastprivilege Will this be re-considered now that the spec is submitted to the RFC Editor Queue?

**Comment by leastprivilege** [comment]
Token exchange can be implemented using our extension grant feature. Is there something specific you are looking for?

**Comment by amadard** [comment]
@leastprivilege Yes, the Act and May_Act claims were the part I was specifically looking for, just because I see them in the spec and wasnt sure on first review how to properly implement them in the extension grants.  I dont have a use case right now, but I am assuming those claims are important for a proper and secure exchange.

**Comment by amadard** [comment]
Should I start a different issue for this conversation?

I did more review, and from my understanding (please correct anything that is wrong), the extension grant validator is covering section 2.1 of the spec, the Request.  The IExtensionGrantValidator has everything needed to fully validate the subject_token and actor_token from what I can tell, other than validating saml1 and saml2 tokens as defined in the spec, which I assume aren't supported by ITokenValidator for extension grants.  I am assuming that the actor_token in the [delegation example](http://docs.identityserver.io/en/latest/topics/extension_grants.html#example-simple-delegation-using-an-extension-grant) would typically be an access_token that was requested by api1 to identify itself.  If the "front_end" client were doing the token-exchange itself, the token for logged in "sub":123 would be the actor_token.

I think that section 2.2 of the spec that defines the Response would require a new implementation of the ITokenService, in my case most likely overriding the DefaultTokenService.CreateAccessTokenAsync.  That is where I could add the act claim based on the actor_token that was passed into the request, and add the may_act claim as appropriate.  

I am not sure how the TokenService would know which users or clients to put in for the may_act, I think it might require an extension of the User or Client classes to support that information.  It could specify the relationship from either direction (Delegator or delegatee), and could have role defined delegation relationships (e.g. everyone in admin role is allowed to be the actor for anyone in the user role, or client1 can be actor for everyone in the user role).

I am not sure how the act and may_act claim would be structured for client actor with client or user subject delegation, because the examples in the spec seem to all show user actor to user subject delegation.  They only have "sub" claims, so I am assuming it would contain "client_id" instead.  From my perspective, the [delegation example](http://docs.identityserver.io/en/latest/topics/extension_grants.html#example-simple-delegation-using-an-extension-grant) shows a client actor with user subject exchange, please correct me if I am wrong.

I was trying to figure out a flow to allow user actor to user subject delegation in IdentityServer with a subject_token and an actor_token, and I think that a logged in user ("admin@example.net") getting a valid token for another user ("user@example.net") to be used as the subject_token in the token-exchange would need a different extension grant that would return a "user@example.net" subject_token and then the logged in user's access token would be the actor_token.  I think that this grant type would be the only place that needs to put in the may_act claim for token-exchange requests, because all other tokens issued would be the actor_token.  I think this new grant type is the only place to get a subject_token, because I can't think of another way for "admin@example.net" to get a valid token for "user@example.net" without "user@example.net" interactions at the time of token-exchange request.

Based on 4.4 of the spec, I think that the may_act claim may be all that is necessary to validate that which user or client is allowed to be the actor, so long as the subject_token includes the may_act claim, the subject_token is validated by IdentityServer, and the subject_token may_act sub/client_id matches the actor_token sub/client_id.  If I don't have an actor_token, I can ignore the may_act, since it is impersonation, and we don't have anything to validate the may_act against.  I personally would block this from happening, I don't want impersonation happening, only delegation.

The spec says :
> For example, the combination of the two claims "iss" and "sub" are sometimes necessary to uniquely identify an authorized actor

but is that necessary when everything is within my one IdentityServer?  I think I could always assume the issuer is my IdentityServer, and any sub is one of my users.

I would really appreciate any feedback on my current understanding.

**Comment by leastprivilege** [comment]
Hi 

token exchange (beyond what we currently have) is not on our "immediate" roadmap - mainly because of other more important priorities.

So please open a new issue where you detail what features are missing for a "complete" implementation of it. thanks!
