### ISSUE TITLE
IDX20804: Unable to retrieve document from: '[PII is hidden]'

### ISSUE THREAD

**Issue by roeb** [IdentityServer/IdentityServer4#2337]
Hi,

I have a problem with IdentityServer4 and my API running as an Azure container instance. My IdentityServer4 and the the secured API runs locally in a Docker container without problems.

As soon as I run the Docker Container as an Azure Container instance I get the following error. Authentication works without problems (Login). But as soon as I call my Web API with a valid Bearer Token I get the following error.

Runtime: .NET Core 2.1-rc1
IdentityServer4-2.2.0

```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'. ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
```

As I said, Local in Docker works without any problems. Has anyone ever had the following problem or does anyone know a solution?

Regards & Thanks
Robert

**Comment by tiwari-abhishek** [comment]
Which flow are you using? Is authentication local or with Azure AD?

**Comment by roeb** [comment]
I‘m using only local auth with username and password. The authentication from User with login/password works fine. 
The Issue comes later, when the API try to validate the Token by the IdentityServer.

**Comment by scottbrady91** [comment]
This error is caused by your API being unable to load the OpenID Discovery Document (/.well-known/openid-configuration)

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by Dark-Bond** [comment]
No.  You can't close it.  I have the exact same issue in the exact same scenario, except I'm not using a Docker Container.  Application works just great on a dev server running the Azure simulator, but fails when published.

You say the error is caused by the API not being able to load an OpenID Discovery document, like I'm supposed to understand what that is or how to fix it.

**Comment by roeb** [comment]
Here, too, the problem still exists.  Local docker environment everything fine.  Once it runs in Azure Container Instances there is the problem.  I wanted to try it today in AKS and see how it behaves there.  Unfortunately I have no starting point for a solution.  The configuration endpoint of the IdentityServer is publicly available.  I can only imagine that Azure Container Instances does not allow routes that contains a dot 🤔

**Comment by skartknet** [comment]
Same issue  here :( Has anyone found a solution? It looks like the endpoint using the Identity Server Authentication doesn't find the configuration. Any workarounds?

**Comment by MeatDuckXp** [comment]
Same here. I was working through the quickstarts sections, was about to test the MVC Client and I got the same error. 

`InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.ChallengeAsync(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, string scheme, AuthenticationProperties properties)
Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAlwaysRunResultFilters()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`

**Comment by kieronlanning** [comment]
I've got this exact issue running in Docker in Azure too (Azure App Services - Linux Containers).

I've disabled the PII masking, so I can see exactly what the URL. What's interesting here is that the URL it says it's 'Unable to object configuration from', when copied into a browser, works just fine.

**Comment by scottbrady91** [comment]
It's a routing issue. Otherwise, the other likely culprit is an https requirement.

**Comment by kieronlanning** [comment]
I've just noticed, when running in Docker the responses from the `.well-known/openid-configuration` endpoint are all `http`, but the entire app is setup to be `https`. 

I've no idea how to turn that on.

**Comment by forlayo** [comment]
Are you setting the Authority as raw domain without https? then that's the issue, change it and it's going to work. 

Not sure why but this was the issue for me.

**Comment by tparikka** [comment]
Same as @forlayo here. In the Startup.cs of my ASP.NET Core 2.1 client application I was configured to use HTTP to reach the authority but in the Debug properties of my IdentityServer project I was set to use HTTPS. Updating the authority to HTTPS resolved the issue.

**Comment by victorud** [comment]
@tparikka  What did you update?

Am having the same issue here

>  IDX20803: Unable to obtain configuration from: '[PII is hidden]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

**Comment by tparikka** [comment]
@victorud In the project settings for my STS I was set to host on HTTPS, but in Startup.cs of the client application my Authority was set to http://localhost:5050 instead of https://localhost:5050. It's part of the ConfigureServices method:

            services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = "https://localhost:50500";
                    options.RequireHttpsMetadata = false;

                    options.ApiName = "api1";
                });

**Comment by Jebarson** [comment]
Use the login.microsoftonline.com for the instance in appsettings.json

"Instance" :  "https://login.microsoftonline.com/"

**Comment by victorud** [comment]
> Am having the same issue here trying to debug on my local, is there any solution to this yet?
> @tparikka the scheme on mine is already on HTTPS yet it's not working
> 
> > IDX20803: Unable to obtain configuration from: '[PII is hidden]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
> > at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
> > at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
> > --- End of inner exception stack trace ---
> > at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
> > at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
> > at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)    --- End of inner exception stack trace ---    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
> > at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
> > at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

I later realised it has to do with the route. The issue has been resolved

**Comment by Jebarson** [comment]
@josepoma Doesn't changing your Instance as i mentioned above work for you?

**Comment by vjarora** [comment]
I am facing the same issue, environment is deployed in IIS in 3 different site 
-Angular App
-IdentityServer4
-WebAPI - ASP.Net Core 2.1
and working fine on localhost and in Intranet, but when I am exposing it to Internet then it is giving the following issue.
{
    "Code": 123,
    "HttpCode": 500,
    "Message": "Error",
    "Description": "IDX20803: Unable to obtain configuration from: 'https://[publicIP]/.well-known/openid-configuration'. 

inner exception : System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://[publicIP]/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\r\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\r\n   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)\r\n   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)\r\n   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel) 

stack trace :    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)\r\n   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()\r\n   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)\r\n   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)"
}

**Comment by manuelpandom** [comment]
I was getting the same error when configuring a MVC web app to use OpenID Connect authentitication agains Identity Server V3. 

I solved this setting the property "MetadataAddress" to the openid configuration, something like 

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
	{
		MetadataAddress = "http[s]://{IdentityServer_IP}:{PORT}/.well-known/openid-configuration"
		...
	});
```

Hope this helps somebody.

**Comment by laball** [comment]
I got the error info too.
```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
```

It takes me 3 days to solve.
Here is what I do.

1. set up the IdentityServer4 in web app:
```c#
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddIdentityServerAuthentication(options =>
            {
                options.Authority = Configuration[AppConfigConsts.AuthorizationSection];
                options.RequireHttpsMetadata = false;    
                options.ApiName = AppConfigConsts.DefaultApiName;
            });
```

config the nginx :
```
	location /connect {
	    proxy_pass http://ip:port;
	}

	location /.well-known {
	    proxy_pass http://ip:port;
	}
```

You should not use the upstream , use ip and port directly.

Hope this helps somebody.

**Comment by D252874** [comment]
i changed it from http to https and now i have the isue that i can't start my iis server anymore

**Comment by DonaldRecord** [comment]
Just throwing this out there for anyone else who has been using ID4 _successfully_ and then runs into this issue. I was connected to my NordVPN when I got it. Disconnected from the VPN, restarted ID4, went back to working fine.

**Comment by VictorUUsoro** [comment]
> @victorud How was it solved?

the route was not correct

**Comment by davidszanto** [comment]
I had the same issue. With IIS I got the error, but using only Kestrel this worked just fine. 
Like for @DonaldRecord, after **disconnecting from VPN** IIS worked just fine for me. 

Hope it helpes someone!

**Comment by AKlaus** [comment]
My 2¢. Started having the same problem in 1 out of 4 environments I have (all Windows VMs). The only related change I made is upgrading `identityServer4.AccessTokenValidation` from `v2.4` to `v2.7`.

Version I'm using:
- `identityServer4.AccessTokenValidation v2.7`
- `IdentityServer4.AspNetIdentity v2.1` 
- `Microsoft.IdentityModel.Tokens v5.4` 
- `System.IdentityModel.Tokens.Jwt v5.4`

**Comment by mattsmall1972** [comment]
I ran into this same issue when running a customer's application with the authorization information removed, so I needed to replace my .  I am not using IdentityServer, but I am thinking my experience might help:

1) In order to see the location that it was using for the document and get past the PII message, I put this in my code to disable the PII message:

 IdentityModelEventSource.ShowPII = true;

I found this by following the link which was in the exception message:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII


2) As Scott Brady says above, there is an OpenID Discovery Document (/.well-known/openid-configuration) that *must* exist somewhere for your authorization provider.  I am a Microsoft Employee using AAD and found this:

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#fetch-the-openid-connect-metadata-document

I used the value https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration for the location of the document and got past the issue.

I think that for anyone seeing a value of "https::/localhost...", then you must find the proper value of your document and configure your application to use that.

If it starts failing when uploaded to a remote server, it may be helpful to determine if that server can reach the document url without issue.  Remove all of the code and run a simple http request from your server to the endpoint to determine if that's the problem.

If this does not help with this problem on this project, please feel free to delete this message.

**Comment by liminany** [comment]
I also has this issues(only enable https has this issues), my sln is(Asp.Net Core 2.2,Deploy to Azure App Service):

- in the Client Application of Startup.cs/ConfigService add these code :

IdentityModelEventSource.ShowPII = true;

options.RequireHttpsMetadata = true;

- in ID4 Server Startup.cs/ConfigServices, add these code:

```

 services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor |
                    ForwardedHeaders.XForwardedProto;
                // Only loopback proxies are allowed by default.
                // Clear that restriction because forwarders are enabled by explicit 
                // configuration.
                options.KnownNetworks.Clear();
                options.KnownProxies.Clear();
            });
```
- in ID4 Server Startup.cs/ConfigService, add these code:

```
app.UseForwardedHeaders();
```
 invoke the url to check the urls:

https://[host-url]/.well-known/openid-configuration

ref:https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#scenarios-and-use-cases

**Comment by garyfawcett** [comment]
I was also getting this error while using Azure B2C and fixed it by correctly setting the Authority in the JWT options, in the startup class ConfigureServices method:
services.AddAuthentication(options =>
{
	options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(jwtOptions =>
{
	jwtOptions.Authority = "https://login.microsoftonline.com/{tenant}.onmicrosoft.com/v2.0";
 
	jwtOptions.Audience = Configuration["AzureAdB2C:ClientId"];
	jwtOptions.Events = new JwtBearerEvents
	{
		//OnAuthenticationFailed = AuthenticationFailed,
	};
});
Where {tenant} is your Azure B2C tenant.

**Comment by tisquip** [comment]
Well, I think for me the reason was that I had pending database migration. After trying all sorts of things to no avail, I just updated my database, then it worked (I just really don't know, maybe something else happened, but when I updated, all I know is that the error message went away)

**Comment by Nastya-Scherbakova** [comment]
Same issue

**Comment by jayeshdshah** [comment]
> I was getting the same error when configuring a MVC web app to use OpenID Connect authentitication agains Identity Server V3.
> 
> I solved this setting the property "MetadataAddress" to the openid configuration, something like
> 
> ```
> app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
> 	{
> 		MetadataAddress = "http[s]://{IdentityServer_IP}:{PORT}/.well-known/openid-configuration"
> 		...
> 	});
> ```
> 
> Hope this helps somebody.

Thank you for saving my day... I have stack of Angular 8 + IdentityServer4 on Windows10. As per your suggestion I made below change and it worked like a charm...

services.AddAuthentication("Bearer")
                .AddJwtBearer("Bearer", options =>
                {
                    options.Authority = "http://localhost/4242";
                    options.Audience = "my-coreapi";
                    options.RequireHttpsMetadata = false;
                    options.MetadataAddress = "http://localhost:4242/.well-known/openid-configuration";
                });

**Comment by robnelder** [comment]
I just had this issue while using IdentityServer4 v2.3.0 running locally with an ASP.NET MVC5 client also running locally. The client connects to the production IdentityServer fine but not the localhost.

I worked around it by adding the following to the MVC client's Application_Start() in Global.asax.cs:

`            #if DEBUG
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 ;
            #endif`

**Comment by pinyo-rungoral** [comment]
In my case error about "JwtBearerOptions.Authority" property incorrect
because when developing i am use https but when deploy at IIS I am use http protocal
