### ISSUE TITLE
Documentation version 1.0.0 PDF (2018-05-15) has incorrect document structure

### ISSUE THREAD

**Issue by Jehoel** [IdentityServer/IdentityServer4#2352]
### Issue / Steps to reproduce the problem

1. Get the release version of the documentation PDF, current version is dated 2018-05-15: https://media.readthedocs.org/pdf/identityserver4/release/identityserver4.pdf
2. Scroll to the Table of Contents page, or look at the Document Structure (Contents) pane in Adobe Acrobat.
3. Observe that all of the headings are flattened under top-level heading 7 "Free and Commercial support": 
![image](https://user-images.githubusercontent.com/1693078/40884249-ff12289a-6707-11e8-912b-e28746796439.png)

4. The headings should retain their structure as they do in the HTML ReadTheDocs format.

**Comment by leastprivilege** [comment]
OK - never tried the PDF feature. Do you know how to fix it?

**Comment by salem84** [comment]
Hi,
I suppose the issue in PDF is due to Sphinx generates TOC in Latex/PDF unlike HTML website; each title in index.rst file produce a single chapter in PDF (also it is only a paragraph).
 
As I know we can improve it in two different ways:
1. The simplest: we add a section "Documentation" before .. toctree:: Sphinx directive, so the TOC is correct, also there are "fake" chapter before "Documentation". An example is visible in Pelican documentation ([HTML](http://docs.getpelican.com/en/latest/) / [PDF](https://media.readthedocs.org/pdf/pelican/stable/pelican.pdf))
2. we insert .. toctree:: after introduction and before other main title in index.rst, so "fake" chapter will be at the end of PDF. An example is visible in Automapper documentation ([HTML](http://docs.automapper.org/en/stable/) / [PDF](https://media.readthedocs.org/pdf/automapper/stable/automapper.pdf))

However I think a general reingineering of TOC must be done in future; I generated a PDF with TOC 2 levels and the result is about 60 chapters... look at [identityserver4-s84-test.pdf](https://github.com/IdentityServer/IdentityServer4/files/2316385/identityserver4-s84-test.pdf)

Some tips can be grabbed from Autofac and Django documentation.

What do you think about it? I'm always there willing to help you

**Comment by brockallen** [comment]
Sure, any PRs to allow this to always be updated would be welcome.

**Comment by salem84** [comment]
I have updated on my fork the docs... you can view at [HTML](https://identityserver4-s84-test.readthedocs.io/) / [PDF](https://media.readthedocs.org/pdf/identityserver4-s84-test/latest/identityserver4-s84-test.pdf)

I apologize for previous commit references in issue history.
If you agree with changes, I'll create the PR
