### ISSUE TITLE
IdentityServer4 in a IIS Web Farm not working properly

### ISSUE THREAD

**Issue by nunorcenteio** [IdentityServer/IdentityServer4#2383]
Hi!

First of all, I'm new to Identity Server but, let me say, that this is a great project!

I'm using IdentityServer4 in ASP.NET Core 2. Everything is working fine when deployed in a single IIS node.

When I login, my browser receive a cookie named ".AspNetCore.Identity.Application" and "idsrv.session".

I need to have high-availability and I activated a load balancer for a second IIS node.

I have the same machine keys configured in IIS and in the web.config of my Identity application.

If I stop my first node (where I was logged in) and start the second node, I expected to be authenticated. Is this supposed, right? When refreshing, the server doesn't recognized me as being logged. The ""idsrv.session" is cleared.

When I stop the second node and start the first node, I do a refresh and I'm automatically logged in.

Can someone give me a hint?

I've being reading documentation for the past two days, I've tried a lot of different approaches but nothing helps :(.

I don't have any relevant logs, don't really know why.

Can someone help me?

Thanks

**Comment by ashtonkj** [comment]
Ok - disclaimer ahead. I am not a contributor to the project, but I am user of it. 

Disclaimer aside - I'm going to go out on a limb here with my response. The biggest potential candidate I see for causing this issue is the signing credentials you are using. When configuring your identity server in Startup.ConfigureServices (or your equivalent), what signing credentials do you set? (I think the samples tend to show it as `services.AddIdentityServer(...).AddDeveloperSigningCredentia()l`).

**Comment by nunorcenteio** [comment]
Thanks for replying. I figured out 5 minutes ago what I was missing :)
I had to configure the DataProtection to store the keys.
That solved the problem :)
