### ISSUE TITLE
Issue with Single Log-out (SLO) #474

### ISSUE THREAD

**Issue by tianqing88** [IdentityServer/IdentityServer4#2411]
A similar issue for closed case #474 in Production Server. I have 3 .net core Apps running on oidc authentication scheme. When running on localhost it is perfectly fine. But is not working in production. Example i have two clients. Client A: abc.123.com, Client B: 123.abc.com. When A is logout, B is still remain as logged in. I guess somehow, it doesn't clear cookies from a different domain. Is there any similar issues and fixes regards to this problem?

**Comment by LL-Zhao** [comment]
I also want to know.

**Comment by leastprivilege** [comment]
any update?

**Comment by regul4rj0hn** [comment]
We've got a similar or maybe related issue in our Production server. I'll try to explain it clearly.
For apps A and B and Identiy Server S:
1) Go to A, get redirected to S and login successfully.
2) Go to B, checks the Authorize endpoint on S and gets auto-logged in via SSO.
3) Logout from the client app A (correctly hitting the EndSession endpoint: SLO). Get redirected to S after successful logout,
4) Client cookie still exists on B, so logout from B as well. Get redirected to S after the logout. _Am I wrong to assume here that EndSession would fail because of the ID token hint will be invalid for B on S?_
5) Back on A, log back in.
6) Go to B, browser still on the IS4 login page, trying to login will result into an error.

Hope that makes sense.
