### ISSUE TITLE
Consider redirect uri scheme blocked list

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2434]
Not that lists of known bad things is ideal, but it won't hurt. Schemes to consider:

javascript:
file:
data:
mailto:
ftp:
blob:
about:
ssh:
tel:
view-source:
ws:
wss:

**Comment by LindaLawton** [comment]
I am kind of think its more the responsibility of the owner of the server to ensure that only valid redirect URIs are created.   What are you planing on doing checking it when the client is verified?  Seams like a lot of unnecessary checking to me.  

_I added a check in my developer console app so that third party developer cant add invalid redirect uris._

**Comment by brockallen** [comment]
> I am kind of think its more the responsibility of the owner of the server to ensure that only valid redirect URIs are created.

Yea, that doesn't always happen :)

**Comment by brockallen** [comment]
merged
