### ISSUE TITLE
IdentityServerAuthenticationService doesn't work well with the new dynamic/policy auth schemes in 2.1

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2489]
Since the dynamic schemes are now going to be used as the default scheme, those names will not line up with the actual cookie scheme being issued at login time. Our logic to augment the cookie with claims does not trigger, and then there's an error when we try to issue the token (it's the "idp claim is missing" exception).

**Comment by Mardoxx** [comment]
What's the issue here? I'm guessing it's to do with https://github.com/IdentityServer/IdentityServer4/blob/6003f606458255666dc33db00714ef0d15969061/src/IdentityServer4/Hosting/IdentityServerAuthenticationService.cs#L59-L62

So I assume it's relying on that `GetDefaultAuthenticateSchemeAsync()` returns cookie auth scheme?

**Comment by brockallen** [comment]
GetDefaultAuthenticateSchemeAsync is now possibly returning a scheme that's not real. There's a new "virtual" scheme feature.

**Comment by brockallen** [comment]
This discussion (https://github.com/aspnet/Security/issues/1832#issuecomment-410330370) makes me think we can't rely upon anything anymore, so just make an explicit "What's Your Cookie Scheme" property on our `AuthenticationOptions`. Yet another thing to configure.

**Comment by brockallen** [comment]
PR submitted

**Comment by brockallen** [comment]
merged
