### ISSUE TITLE
Update Quickstarts

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#2536]
* using templates and dotnet CLI
* using 2.1

etc

**Comment by Ponant** [comment]
How do you want the feeback? It seems you accept PR only for the dev branch.

**Comment by leastprivilege** [comment]
You can either just write your feedback here - or click the "edit on github" button on the doc page.

**Comment by brockallen** [comment]
I finished reworking QS 6-8, and the combined sample.

**Comment by veikkoeeva** [comment]
I'm wondering about https://github.com/IdentityServer/IdentityServer4/pull/2856/files#diff-71f9631bfa2ca3c38575e79f74c3924fR146 and the IETF Best Practice recommendation to not to use implicit flow and move to PKCE even for web clients that if there should be a note a clear note about it? If I didn't read the diff wrong, `AllowedGrantTypes = GrantTypes.Implicit` was changed to `AllowedGrantTypes = GrantTypes.Code`.

As for context: https://medium.com/oauth-2/why-you-should-stop-using-the-oauth-implicit-grant-2436ced1c926, for further links to IETF and other explanation.

**Comment by veikkoeeva** [comment]
I'll add https://brockallen.com/2019/01/03/the-state-of-the-implicit-flow-in-oauth2/ as it explains this well.

**Comment by Ponant** [comment]
@leastprivilege , I need to know what your priorities are.
I went through the first tutorial 1 ClientCredentials and followed it step by step on a windows machine using Visual Studio 2019 preview executing every command that is written and copy pasting the Client Program.cs as it is not present in the rst doc file (you provide a link, though). I can make it run properly but only if I modify the configuration csproj files. In that sense the documentation is somewhat lax.
The main modifications are:
-main async in the client program file needs C# 7.1 which can work if you add `    <LangVersion>latest</LangVersion>
` , as is the case in your template
-the default scaffolding of the dotnet new of the Api gives ` "applicationUrl": "http://localhost:5001;http://localhost:5000"`, which will crash since port 5000 is for IS.
-SSL runs by default in my case, so I need to modify the http string in Client.

All in all the tutorial is lax but it can be fixed by the reader if he goes through the fixing of the above. Do you want to leave it as is or would you prefer to be more careful by including the above?
Also, why not going all SSL in the tuto as this comes as a default and is gradually enforced virtually everywhere? 
Let me know

**Comment by leastprivilege** [comment]
OK - thats good feedback. It would be great if you add the additional steps.

wrt HTTPS - I don't care too much. It's all localhost.

**Comment by Ponant** [comment]
Done

**Comment by Ponant** [comment]
I understand the conclusion in 8_aspnet_identity.rst but, still, it would have been nice to have a tuto that allows one to have a configuration similar to what occurred in 2.0, a full IdentityServerAspNetIdentity with registration etc+ Mvc client + Api. Any insight on that?

**Comment by Ponant** [comment]
So you are downgrading the service. I would not advise a half backed solution.

**Comment by Ponant** [comment]
Its a blue moon or what? @brockallen take it easy and stop being condescending. My last post was an advice, not a complaint. If you make a half backed solution then I take the right to advise you that this is a half backed solution that potentially will be viewed as a downgrade of the free service. If you are offended by that or if you put every github user in the same pot then it's better to shift your view on how open source works. Actually, I was implicitly proposing my help to do it for you, for free ;). But for that I needed to see if 1- you would be interested, 2- which Asp.Net Identity template will be the choice.
