### ISSUE TITLE
Create custom Configuration Stores for External Storage

### ISSUE THREAD

**Issue by PrabhujiMudragalla** [IdentityServer/IdentityServer4#2562]
Hi Team, 

We are planning to migrate our database to Service Fabric Reliable collections, so we are also planning to move Identity Server tables. 
To do that we are trying to create a custom configuration stores for Identity Server as mentioned in below URL:
[Typical Deployment](http://docs.identityserver.io/en/release/topics/deployment.html)
But we are planning to use APIs for accessing the Identity server data instead of database tables. 
Can we extend IClientStore and IResourceStore to use our custom API's and provide identity options. 

Let us know your suggestions/ alternatives on this implementation.

**Comment by scottbrady91** [comment]
Yes, you can write your own stores that call out to APIs instead of using databases directly. What you do inside these stores isn't the concern of IdentityServer, only that you return data.

Just be aware that some of these stores get hit a lot, and putting an HTTP request in the middle of them is going to affect performance.
