### ISSUE TITLE
Refresh Tokens and Grace Periods

### ISSUE THREAD

**Issue by brentlyjdavid** [IdentityServer/IdentityServer4#2610]
We have a potential feature request related to refresh tokens.

We have a situation, where the network is not reliable enough to assume that we will always be getting data back from the server.  For example.  When we refresh a token, we've seen times where the network drops on the trip back, so the actual refresh happens server side but we never get any data back.  Is there any feature built in to IdentityServer4, or something that could be, such as a grace period to call the refresh again (so within a minute or something of the last time that user made the refresh call and with the previously valid refresh token) and basically return us the current state of the refresh token?

We are essentially looking for a way to have the single use tokens, expire in a set time frame (all built in today), but have a fallback to get refreshed token values should any portion of it fail due to network related problems or app crashes, as long as it happened within a set amount of time of the previous call.

If this isn't something i should put here, I can post to SO, but I thought maybe this could be a nice feature to have related to tokens.

Thanks!

**Comment by brockallen** [comment]
>  Is there any feature built in to IdentityServer4, or something that could be, such as a grace period to call the refresh again

You can change the reference token type to be "reuse" instead of "single use".

As for a new feature of a "grace period", this is not such a bad idea... perhaps an easy implementation would be to update the expiration in the DB to be 5m past the current date/time. That way it will expire shortly, but within that period it could be retried.

We will discuss.

**Comment by managerger** [comment]
> You can change the reference token type to be "reuse" instead of "single use".

Unfortunately, reuse can't work with sliding expiration. 
Take a look at the case which can be also fixed with "grace period" feature:
```
RefreshTokenUsage = TokenUsage.OneTimeOnly,
SlidingRefreshTokenLifetime = 180,
AccessTokenLifetime = 60,
RefreshTokenExpiration = TokenExpiration.Sliding,
```
The problem in this configuration the next:
1) After 60 seconds (when AT is expired) I do 2 requests in a row (they have the same expired AT and alive RT)
2) First request gets new AT, deletes old RT and inserts new RT (with new handle)
3) Second request still has old token data, because it was made quickly, in a row.
4) Second request tries to validate AT - it is expired, then it tries to validate RT - it doesn't exists in a store (because first request deleted it and inserted new one with prolonged lifetime).
5) Validation of second request is failed, thus whole request is failed.

**Comment by softwarebybrent** [comment]
I think the extension will work for us like described by @brockallen.  Basically, the one time use tokens are a fixed point in time, until the refresh call comes in, and then you change the expiration date to X minutes past the time of that call.  Maybe that's configurable like it is on the Client object? Default to your 5 minute suggestion above.  Not too concerned about configuration here, but just a nicety.

Either way - as long as we can basically re-try the refresh with the old Access token and RT combination, it should solve our problem we are having today.

Glad to see this is on the 2.3 milestone.  Thanks everyone!

**Comment by brockallen** [comment]
Sorry to keep kicking this down the road, but it's too involved for this release. Moving the milestone.

**Comment by leastprivilege** [comment]
tracking here

https://github.com/IdentityServer/IdentityServer4/issues/3519
