### ISSUE TITLE
Remember Login

### ISSUE THREAD

**Issue by StefAtGithub** [IdentityServer/IdentityServer4#262]
Some time ago there was an issue "Remember my Login", marked as bug. Now I see that the issue is closed. I tried with latest dev version, but it seems that "Remember my Login" is not done until now.
Is it planned to implement it in RC1 ?

**Comment by brockallen** [comment]
You would implement this yourself in the login page logic.

**Comment by StefAtGithub** [comment]
If this featureis not part of idsrv4 you should remove the "Remember Login" checkbox from 
the login pages, otherwise we assume that there is or will be some function behind.
It is confusing for me that @leastprivilege  classified it as bug (#193). In idsrv3 this functionality was not implemented in the login page logic, it was supported by the core services. When you remove functionality from version n to n+1 it would be nice to explain us what is the reason for your decision.

**Comment by brockallen** [comment]
Yes, you're right -- I lost track of the sample code's checkbox feature. That other issue was more tracking session management, which was something else. I'll leave this open as a reminder to fix the sample host code.

**Comment by ChristianRiedl** [comment]
I studied the **idsrv3** sources and I see that the idsrv3 **Remember Login** implementation is not trivial. So I was very happy that @leastprivilege  commented my issue #193 :

_Remember Me is a UI feature. Once we get closer to RTM we will have a standard UI implementation that will support remember me OOB._

Of course I can wait for RTM, but I need to know if I have to work on a solution or if **Remember Login** will be part of the release version.

**Comment by brockallen** [comment]
None of the UI is part of the core anymore in IdentityServer. What's in the "Host" is all sample code, mainly because that's where so much customization took place in IdentityServer3. We did not want to constrain how you wrote those pieces anymore, thus the redesign.

At some point (time permitting) we might have an additional package/library that provides helpers for many of these common things you'd want in the UI (e.g. such as action results that help with consent). I just don't yet know what this might look like -- we've been so busy working on the core, we've not had time to think about these higher order features.

Having said that, I will add an implementation to the sample Host for doing the "remember me" feature. I just can't say when. 

If it makes everyone feel better, I'll remove the HTML element for the time being.

**Comment by brockallen** [comment]
Any code related to it is now removed. I'll leave this open as a feature request to add something back to the sample host.

**Comment by ChristianRiedl** [comment]
Thank you for the information. I am happy to switch my solution soon to AspNetCore / IdSrv4 because the new structure is much cleaner. And I am very happy with the seperate AspNet Identity, EntityFramework, Quickstart packages.  Probably I am too close on your heels, and I want to get information earlier than you have time to write some docs.

**Comment by StefAtGithub** [comment]
I started to consider where to implement **Remember Me**. There are several places where I can imagine to store some cookie information (in the browser ? in Identity Server ?) or to extend the lifetime of the cookie. But I have not the experience to calculate the security drawbacks of such solutions. It would be great when one of the authors other expert can give me a hint where is the best place to implement it.

**Comment by leastprivilege** [comment]
"Remember me" means that you set a persistent cookie - it's a UI thing.
