### ISSUE TITLE
Replace/add custom token endpoint Url

### ISSUE THREAD

**Issue by smadurange** [IdentityServer/IdentityServer4#2692]
I have been unable to find any information in the docs on this. IdentityServer4 by default uses "connect/token" Url to issue tokens. I'm trying to migrate an older application to use IdentityServer4. The older app has been using a different token endpoint from the one used by IdentityServer4. 

So, for backward compatibility I need to either override the token endpoint so that the older clients can get the token from "api/token" instead of "connect/token" or provide a second endpoint "api/token" to issue tokens. Is this possible with IdentityServer4 and how to do this?

**Comment by leastprivilege** [comment]
I would suggest you use URL re-writing at the host to accomplish this.

**Comment by smadurange** [comment]
Thanks for the quick response. Followed [this](https://stackoverflow.com/a/49696147/10104979) answer on SO and rewrote the Url. That's working even though could not find a way to update the OpenID discovery document at ~/.well-known/openid-configuration.

**Comment by arnaldo-infinite** [comment]
You can add your custom endpoints by using CustomEntries which is explained in the docs. Yet I don't think you can edit an existing endpoint. Since your problem is resolved now, let it be so, just for your info.

http://docs.identityserver.io/en/release/topics/add_apis.html?highlight=Discovery%20Endpoint
