### ISSUE TITLE
Cookie length should be less than or equal to 4096 characters.

### ISSUE THREAD

**Issue by balkarov** [IdentityServer/IdentityServer4#2697]
### Steps to reproduce the problem:
1) Download [IdentityServer4.Samples](https://github.com/IdentityServer/IdentityServer4.Samples)
2) Open solution `IdentityServer4.Samples-release\Quickstarts\3_ImplicitFlowAuthentication\Quickstart3_ImplicitFlowAuthentication.sln`
3) Add to MvcClient Statup.cs `options.ResponseType = "id_token token";`
4) Add certifate generate by openssl (for localhost)
[localhost.zip](https://github.com/IdentityServer/IdentityServer4/files/2464110/localhost.zip)
For generate cert I use [instruction ](https://www.teilin.net/2018/07/05/self-signed-certificate-and-configuring-identityserver-4-with-certificate/)

5) Add to QuickstartIdentityServer Startup.cs `.AddSigningCredential(GetCertificate())` instead `.AddDeveloperSigningCredential()`
and
```csharp
public static X509Certificate2 GetCertificate()
{
    var fileName = Path.Combine(Environment.CurrentDirectory, "idsrv.pfx");
    return new X509Certificate2(fileName, "123456");
}
```
6) Add to QuickstartIdentityServer Config.cs `AllowAccessTokensViaBrowser = true` for mvc Client

After login I get warning in Chrome browser

> Set-Cookie header is ignored in response from url: http://localhost:5002/signin-oidc. Cookie length should be less than or equal to 4096 characters.

I tried to update projects to AspNetCore 2.1 and update Identity server 2.2.0, but it did not help me.

What am I doing wrong?

**UPDATE:**

I tried use this [certificate generator](https://gist.github.com/svrooij/ec6f664cd93cd09e84414112d23f6a42#file-certificates-cs) for production . And nothing warnings. Is it right use this generator in AddSigningCredential for production?

![34](https://user-images.githubusercontent.com/6030335/46729349-be4d6b80-cc8d-11e8-96b0-f02bf678ed23.gif)

**Comment by ngruson** [comment]
This is actually coming from your browser. Because you get both the identity token as well as the access token through the browser channel, the cookie gets too large for your browser. Why do you want to get the access token this way? Have you also tried using hybrid flow with auth code? ResponseType would then be "code id_token". It's also in the samples.

**Comment by balkarov** [comment]
So why the example use Impicit? Is it right use Hybrid flow for browser-based applications?

**Comment by balkarov** [comment]
I have changed to `AllowedGrantTypes = GrantTypes.HybridAndClientCredentials` and `options.ResponseType = "code id_token";` and get the same warning

**Comment by balkarov** [comment]
And I tried use certificate (`AddSigningCredential`) in this project too `IdentityServer4.Samples-release\Quickstarts\5_HybridFlowAuthenticationWithApiAccess` and I have the same problem

**Comment by balkarov** [comment]
I tried use this certificate generator for production . And nothing warnings. Is it right use this generator in AddSigningCredential for production? Maybe my certificate (idsrv.pfx) is wrong?

**Comment by ngruson** [comment]
So with AddDeveloperSigningCredential the error doesn't occur? Signing certificate shouldn't affect the size of the cookie, I'd think.

**Comment by balkarov** [comment]
With AddDeveloperSigningCredential has not warning

**Comment by balkarov** [comment]
@ngruson @brockallen any idea?

**Comment by ngruson** [comment]
I took your certificate for a spin and I couldn't reproduce your issue. What browser are you using? Can you reproduce the issue in another browser?

**Comment by balkarov** [comment]
@ngruson Google Chrome 69.
Another browsers have not the problem. Only in chrome. 
PS: I tried on several computers and clear all cookies and cache.

**Comment by ngruson** [comment]
I could not reproduce the issue with Chrome (version 69.0.3497.100) using your certificate. Apparently, your cookie exceeds Chrome's limit of 4069 bytes. https://documentation.devexpress.com/AspNet/11912/Common-Concepts/Cookies-Support/Cookie-Limitations

Can you try running IdSrv and your client app in IIS instead of IIS Express?

**Comment by balkarov** [comment]
How did you use my certificate without password? I did not send password by certificate

**Comment by ngruson** [comment]
Password for certificate is in your initial post :)

**Comment by balkarov** [comment]
Tried this project
[5_HybridFlowAuthenticationWithApiAccess.zip](https://github.com/IdentityServer/IdentityServer4/files/2464108/5_HybridFlowAuthenticationWithApiAccess.zip)
Run MvcClient and QuickstartIdentityServer

**Comment by balkarov** [comment]
![34](https://user-images.githubusercontent.com/6030335/46729337-b5f53080-cc8d-11e8-9abe-46b7ac6b1ac8.gif)

**Comment by balkarov** [comment]
@ngruson did you try?

**Comment by balkarov** [comment]
@ngruson @brockallen any idea?

**Comment by ngruson** [comment]
I could reproduce your issue, but it doesn't have anything to do with the signing certificate. Even with AddDeveloperSigningCredential, Chrome complains about the cookie being too large. Some browsers like Chrome and Safari have cookie size limitations.

Using the solution from your zip, I get a 'Keyset does not exist' exception. When using hybrid flow like sample 5, I don't get the cookie error in Chrome. Because in that case, the access token is not stored in the cookie and the client is getting the token by exchanging the authorization code for an access token via the backchannel.

**Comment by balkarov** [comment]
Try add my certificate to your storage in Windows. 
But why I reproduce this issue with my certifiacate but with AddDeveloperSigningCredential I do not reproduce?
But big cookies from identity is problem, is not it? Because Chrome can reject this cookies.
And if you can reproduce this problem, how resolve the problem?

**Comment by balkarov** [comment]
I tried remove all claims, but cookies was big too. And I have not idea how solve big cookie problem

**Comment by ngruson** [comment]
Have you tried setting AllowAccessTokensViaBrowser to false and using hybrid flow as is done in sample 5?
`options.ResponseType = "code id_token";`

That way the access token doesn't end up in the cookie.

**Comment by balkarov** [comment]
@ngruson but `5_HybridFlowAuthenticationWithApiAccess.zip` has not AllowAccessTokensViaBrowser and set options.ResponseType = "code id_token";

**Comment by balkarov** [comment]
@ngruson do you have other idea?

**Comment by Robban1980** [comment]
@balkarov To get around the 4096 issue, use Session Cookies in a distributed storage. So that .Net only sends the session cookie key to the FE while the real values are stored in a distributed storage. This will result in a small cookie that does not exceed the browser limits. If you will ever only have 1 server of you RP then you can also use the in memory storage for the cookie.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
