### ISSUE TITLE
AuthenticationManagerExtensions does not provide an overload that allows for setting persistent cookies 

### ISSUE THREAD

**Issue by ericgreenmix** [IdentityServer/IdentityServer4#272]
Need to be able to set persistent cookies to support "remember me" type features

**Comment by leastprivilege** [comment]
Yes - I noticed that as well. thanks!

**Comment by ChristianRiedl** [comment]
It is easy to work arround and create the _IdentityServerPrincipal_ and use it to call _AuthenticationManager.SigninAsync_. But this is only the half Story. I am not able to deliver the _AuthenticationProperties_ including _IsPersistent_ and _ExpiresUtc_ to the OpenIDConnect and cookie handler in my MVC application.  
The authentication properties are serialized properly to a _AspNetCore.Application_ cookie but the authentication properties read by the OpenID authentication handler in the MVC application looks different. I will continue to analyze it but I have not enough knowledge of the AspNetCore authentication components. I will try to debug it.

**Comment by leastprivilege** [comment]
Why OpenID Connect ?? You are only supposed to sign in the user.

**Comment by ChristianRiedl** [comment]
I have now a solution where I set the cookie properties to persistent with some expiration date in my MVC's apps _OpenIdConnect.OnTokenValidated_ event. Than I was looking how _AccountController.Login_ can deliver the "Remember Me" checkbox info together with the implicit flows authentication response. This response contains an _expires_in_ field but it contains the "constant" clients token lifetime parameter. The _state_ contains the serialized _AuthenticationProperties_ but it cannot be changed during login because as I understand, the specs require that they are a copied from the request _state_ field. So in my current solution I saw only the chance to use  some claim to deliver the "remember me" information. I misused standard "amr" claim for this purpose and for my purpose "remember me"  is working now as expeected. But I think it is not really a clean solution so I studied how you solved the problem in idsrv3 and found out that it was a quite different approach, and I think you surely have a good reason not to do it in the same way in idsrv4. Anyhow my solution is working for my needs.

**Comment by leastprivilege** [comment]
I think you are misunderstanding the whole thing. "Remember me" on the idsrv login page is for the idsrv cookie. Not the client.

**Comment by ChristianRiedl** [comment]
You are right, it seems to work. I tried the same thing in the beta5 version and it failed for some  reason.
So I assumed that I have to make the client cookie persistent, which is a bit more complicated.
Thank you.

**Comment by leastprivilege** [comment]
done on dev
