### ISSUE TITLE
Need the ability to override ScopeValidator

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2737]
**Is your feature request related to a problem? Please describe.**

I have an [extension grant](https://github.com/ghstahl/Generic-Security-Token-Service/blob/master/docs/arbitrary_resource_owner.md) where I want to pass in an arbitrary list of scopes via the "scope" argument.
The extension grant is used to generically mint an access_token, and configuring a client to have a list of allowed_scopes is not viable.  Those scopes are not known to the service and must be passed in.

**Describe the solution you'd like**
I would prefer that you actually change usage of ScopeValidator to IScopeValidator.  That would have made it easy to hook assuming the IScopeValidator had the methods I want to override. 
i.e. AreScopesAllowedAsync

A quick workaround is to make some methods virtual  
```
 public class ScopeValidator
 { 
     public virtual async Task<bool> AreScopesAllowedAsync(Client client, IEnumerable<string> requestedScopes){}
etc.
}
```
so I can do this;
```
 public class MyScopeValidator : ScopeValidator
 {
        public MyScopeValidator(IResourceStore store, ILogger<MyScopeValidator> logger) : base(store, logger)
        {
        }
        public override async Task<bool> AreScopesAllowedAsync(Client client, IEnumerable<string> requestedScopes)
        {
            return true;
        }
 }

 builder.Services.RemoveAll<ScopeValidator>();  // remove original
 builder.Services.TryAddTransient<ScopeValidator, MyScopeValidator>();  // use mine instead
```

**Describe alternatives you've considered**
The alternatives are messy as the base implementation expects that I pass in a scope that exists and is allowed.  I was going to have a burner scope called "remove_me", and all clients are allowed to have only one allowed scope, the "remove_me" scope.

I can pass in my arbitrary scopes via a new arbitrary_scopes argument and clean up the mess on the way out.
```
scope: offline_access remove_me
arbitrary_scopes: a b c d e
```
I would just prefer to have
```
scope: offline_access a b c d 
```

**Comment by brockallen** [comment]
relevant: #1640

**Comment by ghstahl** [comment]
@brockallen The referenced issue: #1640 indicates breaking changes.
For the time being, can I convince you to mark the methods that are overridable in ScopeValidator as virtual.

This wouldn't be a breaking change, because nobody can inherit from this current class and override anything.  This would allow that.  If someone is inheriting from ScopeValidator, which I doubt as it serves no purpose, those now virtual methods in the base wouldn't change anything.  

Unless some crack-pot is actually inheriting and using your same method names, which means that they need to have their code broken :)

**Comment by gusztavvargadr** [comment]
@ghstahl we ended with the following approach.

- The resource store recieves the list of requested scopes at https://github.com/IdentityServer/IdentityServer4/blob/63a50d7838af25896fbf836ea4e4f37b5e179cd8/src/Validation/Default/ScopeValidator.cs#L134. Even if we have dynamic ones which cannot exist in any static stores by defintion, we use a custom implementation here to return the "valid" requested scopes based on some logic (e.g. if a client has a given static scope, we allow dynamic scopes based on a pattern like regex).
- Since the client's `AllowedScopes` property is an `ICollection`, we can use a custom implementation here as well that e.g. proxies to an underlying collection, but extends the logic of the `Contains` method similarly. Even if dynamic scope is not in the list of explicit scopes, `Contains` simply returns true if it matches a pattern, similar to above.

This way you can use the original implementation of the `ScopeValidator` without the need for extending it. Hope this helps!

**Comment by cleftheris** [comment]
@ghstahl maybe a pull request will be easier for the maintainers to accept.

**Comment by ghstahl** [comment]
@gusztavvargadr 
I grasp what you are trying to do, but the calls to FindResourcesByScopeAsync have no client context.  

The question I am trying to answer is; 
For this client for this request passing in arbitrary scopes can I state that they are valid and allowed?

I have theorized that I could introduce a SCOPED object that tracks context which I could inject into my store, but I felt that I was going down an unmaintainable rabbit hole with that.  

@cleftheris I did issues a pull request awhile back as a hint as to what I need.  @brockallen and @leastprivilege have a bigger vision of what the final outcome is going to be.

**Comment by brockallen** [comment]
We know that our scope processing code is messy. We plan to re-architect in the next major version when we can make breaking changes.

**Comment by cleftheris** [comment]
@brockallen Are u referring to `IdentityServer4` v3 or more distant future stuff. What is suggested above is a solution that will allow customization as we all await for the next release. 

Introducing an interface should not produce any breaking changes at the moment.
On the other hand scenarios like wildcard scopes are required for protecting Financial APIs in Europe seem almost impossible to implement at the moment without overriding the ScopeValidator. 

PS1: Can we do something to help?
PS2: I have gone as far as to declare and consent to dynamic (wildcard) scopes using the very helpful suggestions by  @gusztavvargadr. Although I hacked my way into granting access with dynamic scopes, those scopes are not added to my tokens.

**Comment by cleftheris** [comment]
@brockallen one more thing I have found that here is another player that may kick out a scope. my wildcard scope logic breaks because the `IntrospectionResponseGenerator` kicks out of the persisted grant my extra scope 😭. https://github.com/IdentityServer/IdentityServer4/blob/73b5a0ca01cbe15f3a247783003080ec47536adc/src/IdentityServer4/src/ResponseHandling/Default/IntrospectionResponseGenerator.cs#L88

**Comment by leastprivilege** [comment]
tracking here

https://github.com/IdentityServer/IdentityServer4/issues/3520
