### ISSUE TITLE
Client Token in API Gateway with IS4

### ISSUE THREAD

**Issue by Mortenkp91** [IdentityServer/IdentityServer4#2750]
Hi IdentityServer Team.

I'm in the progress of implementing a microservices architecture with a single entry endpoint for my clients, a API Gateway. I would really like to use the features of IdentityServer4, but I'm in doubt of how to implement my desired authentication flow. 

1). Client (SPA) passes user credentials to the API Gateway, which passes them further to my Authorization/Authentication Services.

2). The Auth Service validates credentials and issues some form of opaque token, which is passed back to the client through the API Gateway.

3). The Client sends the token as a header to each request. The API Gateway exchanges this opaque token to a JWT from the Auth Server and stores it in a cache. The JWT is then attached to all downstreaming requests and my internal microservices validates the JWT (Issuer, Audience).

Does the IdentityServer supports this kind of flow? Can you point in the direction of documentation, which explains this?

Thanks in advance and keep up the good work!

**Comment by leastprivilege** [comment]
I would have a couple of questions on the usefulness/effectiveness of this solution - but the general answer is yes since IdentityServer is a just a framework.

That being said - 

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
