### ISSUE TITLE
Sometimes get a "idp claim is missing" with AspNetIdentity when authorizing

### ISSUE THREAD

**Issue by liamdawson** [IdentityServer/IdentityServer4#277]
```
System.InvalidOperationException: idp claim is missing
   at IdentityServer4.Extensions.PrincipalExtensions.GetIdentityProvider(IIdentity identity) in IdentityServer4-1.0.0-rc1\src\IdentityServer4\Extensions\PrincipalExtensions.cs:line 184}	System.InvalidOperationException
```

IS4 entries in project.json:
```
"IdentityServer4": "1.0.0-rc1",
"IdentityServer4.AspNetIdentity": "1.0.0-rc1",
"IdentityServer4.AccessTokenValidation": "1.0.0-rc1" (resolving to 1.0.1-beta1)
```

I'm using ASP.Net Core Identity, and I've included the IdentityServer4 token validation library (I want to secure an api for user creation etc as part of the same service).

Here are the claims that _are_ set on the current identity:

    [0]: "sub: 3b26b2f3-ed9d-4ca0-9fd1-cb686484002d"
    [1]: "name: liam@example.com"
    [2]: "AspNet.Identity.SecurityStamp: eccf3972-e976-450d-a5a2-3be969616786"
    [3]: "role: sysadmin"
    [4]: "mp.sysadmin: true"
    [5]: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname: Liam"
    [6]: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname: Dawson"

Is this just a "we should allow returning null for the provider"? Or is there a further underlying issue/misconfiguration? In this instance, I'm only supporting one IDP, so I don't personally mind a bandaid fix.

**Comment by leastprivilege** [comment]
How do you sign in the user?

**Comment by liamdawson** [comment]
Via a login endpoint. In this instance, the idp claim issue arose after automatically being accepted as being logged in (via cookies).

**Comment by liamdawson** [comment]
Entirety of the login endpoint:

```
[AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model, string redirectUrl = null)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage ?? e.Exception?.Message); 
                _logger.LogWarning("Login request was invalid. Errors: {errors}, Password provided for {username}: {password_provided}.",
                    errors,
                    model.Email,
                    !string.IsNullOrEmpty(model.Password));
                return StatusCode(StatusCodes.Status400BadRequest);
            }

            var result = await _signInManager.PasswordSignInAsync(model.Email,
                model.Password,
                model.RememberMe ?? false,
                true);

            if (result.Succeeded)
            {
                return Redirect(string.IsNullOrEmpty(redirectUrl) ? "/" : redirectUrl);
            }

            return StatusCode(StatusCodes.Status403Forbidden);
        }
```

**Comment by leastprivilege** [comment]
I see - so it maybe happens when the gets "slided" ? @brockallen ?

**Comment by kdaveid** [comment]
I have made the same experiences. Usually this happens when (in dev) I restart the auth server (IdentityServer4) but not the MVC client and make a new request to an [Authorize]'d method within MVC app. The exact behavior I'll probably see today as I'll go further with implementing.

**Comment by brockallen** [comment]
Possibly. I did have a reminder for myself to look into this.

**Comment by ManuelRauber** [comment]
I can confirm this behavior using ASP.NET Core Identity, too. 

SPA with Implicit using the popup mode. Code is the same as in your quickstarter examples.

**Comment by brockallen** [comment]
The cookie does not lose any claims when it slides, but it will lose claims if the security stamp is invalidated. Is this perhaps what you're running into?

**Comment by brockallen** [comment]
BTW, the properties are not lost so what we'll have to do is either 1) store these crucial claims in the properties, and then reload the claims from the properties, or (unfortunately) 2) in our AddAspNetIdentity we replace the security stamp validator with all of the exact same logic as the built-in one, but instead we reload from the current claims rather than from the DB.

**Comment by liamdawson** [comment]
> security stamp validation

How exactly is this validation performed? As in, is it ASP.Net identity related, and could it happen due to a server restart (I haven't explicitly set any secrets or anything about Identity)

**Comment by brockallen** [comment]
It's automatic within ASP.NET Identity. When anything related to the user's authentication changes (password, 2fa settings, email settings, etc). You can tell by the security stamp claim changing in the user's cookie.

If you can't tell, then can you narrow down the exact repro steps so I can make sure what I'm seeing matches what you're seeing? Thanks.

**Comment by liamdawson** [comment]
Unfortunately, I haven't found a consistent repro. Haven't made any changes to the user, though, at all.

**Comment by brockallen** [comment]
To test this I did several things:

1) set the cookie to be sliding and set the expiration to be low so i could see when the cookie slid. when the cookie slides i see all the same claims, so that's why i'm not thinking it's that.

2) login and then change the user's 2fa settings (or change password, or something else to affect the security stamp). then i saw that the claims issued at login time as lost (including idp). since the cookie renewal is done within the cookie middleware (and not from the mvc code) then we don't have a chance to augment the claims being added so you lose the crucial claims issues issued at at login time (they just reload claims from the ASP.NET Identity DB). that's why i opened the issue in the ASP.NET Identity repo, as this is not ideal behavior IMO.

**Comment by takazm** [comment]
I am getting the same exception idsvr aspnet core, client aspnet core. Also happens when auto authenticated through cookie.

>   Unhandled exception: System.InvalidOperationException: idp claim is missing  .....

> at IdentityServer4.Extensions.PrincipalExtensions.GetIdentityProvider(IIdentity identity)

**Comment by damienbod** [comment]
I have this problem as well, OpenID Connect Implicit Flow. 

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow

I can reproduce it by logging on directly to IdentityServer4, and then starting the SPA and the Implicit Flow login request causes this problem.

Greetings Damien

**Comment by brockallen** [comment]
Ok, I now understand better what's happening. ASP.NET Identity always reloads the user's claims from the DB every 15m by default. This is done by the security stamp validator, but that behavior is odd given that it seems orthogonal the intended purpose of the security stamp validator.

Anyway, I am now very confident that this is the reason behind this issue. I'll keep everyone posted on what we're going to do.

**Comment by brockallen** [comment]
Ok, I've added a custom security stamp validator to not reload claims from the DB. IdentityServer4.AspNetIdentity 1.0.0-rc1-update2 has been released to NuGet. Please test it and let us know how it's working.

**Comment by hmheng** [comment]
I got the same error all the time when i try to authenticate my xamarin app with AspNetIdentity. 
![image](https://cloud.githubusercontent.com/assets/11830387/18538702/611b891c-7b43-11e6-97d6-e22f9540575c.png)
Is it the same issue as above?

**Comment by kdaveid** [comment]
Ok, so there is what I experienced so far. **Before** `1.0.0-rc1-update2` the missing idp issue occurred when I signed out of the client (MVC app) but the idsvr was **offline** and could not receive the redirect/offline request.

Sign out in mvc:
```
await HttpContext.Authentication.SignOutAsync("Cookies");
await HttpContext.Authentication.SignOutAsync("oidc");
```

When I then started an instance of idsvr and reloaded the mvc page or tried to get to an secured page ([Authorized]) it would throw the `System.InvalidOperationException: idp claim is missing`. 

Doing these steps is probably not the use case and I haven't digged into the whole problem so I don't know if this is by design or just me being inconsistent in (re-)starting servers...

Anyway, with `1.0.0-rc1-update2` this does not happen anymore.

**Comment by damienbod** [comment]
I have updated and done some initial tests. I cannot reproduce this problem anymore.

Greetings Damien

**Comment by brockallen** [comment]
Ok, good to hear. Thanks.

**Comment by aggieben** [comment]
@brockallen I'm experiencing this issue as well.

> Ok, I now understand better what's happening. ASP.NET Identity always reloads the user's claims from the DB every 15m by default. This is done by the security stamp validator, but that behavior is odd given that it seems orthogonal the intended purpose of the security stamp validator.

I don't understand this.  Why would periodically reloading the user's claims cause this problem?

**Comment by brockallen** [comment]
> I don't understand this. Why would periodically reloading the user's claims cause this problem?

Because idp is a claim captured at login time, and is not something stored in the DB.

**Comment by aggieben** [comment]
Ok, I follow that.  This issue appears for me right off the bat though, and it's 100% of the time - it smells like a misconfiguration on my part, but I am having a hard time figuring out what it would be.

**Comment by aggieben** [comment]
For anyone else who might have landed here: It's important to call `app.UseIdentityServer()` before calling `app.UseMvc()` in the `Configure()` method of the `Startup` class.  Getting them out of order will result in this issue as well.

**Comment by artiomchi** [comment]
@brockallen @aggieben 
I'm upgrading an app that was previously using `IdentityServer3`. Because of the way it work, the identity server was hosted under /auth, so that was the authority for external apps.

Moving on to `IdentityServer4`, I can have the root url be the authority (nice, by the way!), but I've got external clients that authenticate with our system, so changing the authority url is no easy feat. I've experimented with the QuickStart6 project, and tried the following:

```csharp
app.UseIdentity();

app.Map("/auth", authApp =>
{
    authApp.UseIdentityServer();
});

app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}/{id?}");
});
```

This causes the aforementioned `idp claim is missing` error. Authenticating in the API project works well, but authenticating from the MVC app does now. Even though `UseMvc()` is registered after `.UseIdentityServer()`, I'm guessing the fact that it's under a child url is causing this issue.

Is there a better way to do this, or does this mean this issue is still active?

**Comment by liamdawson** [comment]
@artiomchi the map method doesn't fall through, as such, to the middleware underneath - therefore, MVC is not configured for the `/auth` routes. What happens if you copy the use mvc method into the `Map` method?

**Comment by artiomchi** [comment]
Nope, seems to be running into the same issue.

I've tried
```csharp
app.Map("/auth", authApp =>
{
    authApp.UseIdentityServer();
    authApp.UseMvcWithDefaultRoute();
});
```


Actually, doing some more testing and I uncovered some interesting things..

1. Logging out of both server and client sites, clearing cookies. Adding `UseMvcWithDefaultRoute()` as part of the `/auth` Map.
When I try to go to the secure page on the client, it sends me to the login page (BUT it's on `/auth/account/login`, because of the new mvc rule, styles and js fail to load). BUT the authentication process goes through!
2. Using `UseMvc()` instead of `UseMvcWithDefaultRoute()` in `/auth`. Cleared cookies. When trying to go to the secure page, I get redirected to `/auth/account/login`, which returns a 404. Fixing the url (removing auth), sends me to the login page, but after logging in I get a `idp claim is missing`.
3. not adding `UseMvc()` at all for `/auth` has the same effect as in point 2, including the redirect to `/auth/account/login`

So my guess is that within IdentityServer, the base url gets set, which affects all requests and URL builds to the site, including redirects to the login pages.

I did a quick glance at the code, and something like that is being set here, but without a deeper code analysis, I might just be looking at a red herring :)  
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Hosting/BaseUrlMiddleware.cs#L28

**Comment by artiomchi** [comment]
P.S. Just tried restricting the child route to only catch the Connect controller, and it behaves the same as points 2/3 above

```csharp
app.Map("/auth", authApp =>
{
    authApp.UseIdentityServer();
    authApp.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "Connect/{action=Index}/{id?}",
            defaults: new { Controller = "Connect" });
    });
});
```

**Comment by liamdawson** [comment]
You can override the login/etc urls when you add identity server in the
configure services section. Maybe combining your first attempt with that to
ensure it goes to the right page for JS etc would be a temporary
workaround?

**Comment by artiomchi** [comment]
So... You mean something like this?

```csharp
services.AddIdentityServer(x =>
    {
        x.UserInteraction.LoginUrl = "/account/login";
    })
```
Nope.. It builds the login url based on the relative path. Just to be sure, I changed it to `/account/login2`, and I've been redirected to `/auth/account/login2`.

Could this issue be re-opened or a new issue created for this, as this means I can't use the IS4 at all in my current environment, and that prevents me from upgrading to ASP.NET Core MVC :(

**Comment by leastprivilege** [comment]
open a new issue

**Comment by antonioromano** [comment]
I'm experiencing the same issue, I'm using IdentityServer4 and from time to time I found in logs 'Unhandled exception: System.InvalidOperationException: idp claim is missing' or 'IdentityServer4 message: idp claim is missing stack: at IdentityServer4.Extensions.PrincipalExtensions.GetIdentityProvider(IIdentity identity)'.
When I experience this the only solution is to logout and login again

**Comment by YZahringer** [comment]
The issue is back with version `2.0.0-rc1`.

**Comment by gato-negro** [comment]
Same as @YZahringer after upgrading to 2.0.0-rc1

**Comment by nukec** [comment]
Same issue here:
`InvalidOperationException: sub claim is missing`

**Comment by gato-negro** [comment]
Any updates on this?

**Comment by antonioromano** [comment]
Since this issue has been closed I opened a new one here: https://github.com/IdentityServer/IdentityServer4/issues/1573
Please support and comment it

**Comment by brockallen** [comment]
Just as a follow on note here about this issue. This error happens when you don't have the main authentication cookie scheme set as the default sign-in scheme in ASP.NET Core. This is usually the case when you use ASP.NET Identity, because it internally set the sign in scheme to be the external authentication cookie scheme.

**Comment by sjh37** [comment]
If it helps, I have just got this problem:

**Nuget packages:**
IdentityServer4 v2.3.2
IdentityServer4.AspNetIdentity v2.3.0
IdentityServer4.EntityFramework v2.3.2

**Stacktrace:**
System.InvalidOperationException: idp claim is missing
   at IdentityServer4.Extensions.PrincipalExtensions.GetIdentityProvider(IIdentity identity) in C:\local\identity\server4\IdentityServer4\src\Extensions\PrincipalExtensions.cs:line 203
   at IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator.ProcessLoginAsync(ValidatedAuthorizeRequest request) in C:\local\identity\server4\IdentityServer4\src\ResponseHandling\Default\AuthorizeInteractionResponseGenerator.cs:line 160
   at IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator.ProcessInteractionAsync(ValidatedAuthorizeRequest request, ConsentResponse consent) in C:\local\identity\server4\IdentityServer4\src\ResponseHandling\Default\AuthorizeInteractionResponseGenerator.cs:line 83
   at IdentityServer4.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, ConsentResponse consent) in C:\local\identity\server4\IdentityServer4\src\Endpoints\AuthorizeEndpointBase.cs:line 81
   at IdentityServer4.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\Endpoints\AuthorizeEndpoint.cs:line 55
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 54
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 69
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by sjh37** [comment]
In order to get the following working again:
```c#
services.AddAuthentication()
    .AddCookie("Cookies")
```

I had to delete the users from the database, then re-add them. And magically `idp claim is missing` went away. So changing the authentication scheme **after** a user is created is going to end up with this error.
