### ISSUE TITLE
Storing token in redis cache

### ISSUE THREAD

**Issue by ASGOUD** [IdentityServer/IdentityServer4#2785]
Hi All,

I would like to store identity server token into redis cache to manage load balancing activity. 

Progress Till now with the approach followed in steps.

- I have added Addoperationalstore like mentioned below..

 .AddOperationalStore(options =>
                    {
                        options.RedisConnectionString = Configuration["CacheConnectionString"];
                        options.Db = 7;
                        options.KeyPrefix = "IdentityToken";
                        options.ConfigurationOptions = operationalStoreOptions;
                    })
                    .AddRedisCaching(options =>
                    {
                        options.RedisConnectionString = Configuration["CacheConnectionString"];
                        options.Db = 5;
                        options.KeyPrefix = "IdentityRedis";
                        options.ConfigurationOptions = CachingStoreOptions;

                    })
But still it is storing only configuration data related to client but not storing token into redis. 
Can you suggest or having any inputs on this.

Thanks & Regards,

**Comment by ASGOUD** [comment]
Please help us to resolve the mentioned issue as we are almost closer to production movement.

**Comment by leastprivilege** [comment]
This `.AddOperationalStore` method is not coming from us since we don't have built-in Redis support.

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
