### ISSUE TITLE
Add version information

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#2822]
* at startup time
* on UI on home page

**Comment by leastprivilege** [comment]
done on patch branch - merged to dev.

**Comment by leastprivilege** [comment]
I don't follow. The version gets put into the log files and the **sample** UI.

**Comment by VictorioBerra** [comment]
@leastprivilege 

Gotcha, I don't see the version in the Quickstarts which is good.

I will say though, I frequently look at the commits to IS4, especially stuff in Host to see if there are improvements or fixes i should be making to my own host. I think there are others out there like me and some people might add a version to their UI which might not be the best security practice. I don't know if that is grounds for not showing the version in Samples because I do think it is nice to see on demo.identityserver.io when testing, but maybe add a comment saying ``// You should probably not display this version in production`?
