### ISSUE TITLE
Bearer configured for IdentityServer... does not supports signin

### ISSUE THREAD

**Issue by MrGroovy** [IdentityServer/IdentityServer4#2916]
A closed issue is here: https://github.com/IdentityServer/IdentityServer4/issues/2846

But i dont understand what the error is. Please explain what this means.

**Comment by thePmr** [comment]
It's just a warning notification (of 'error' level though) that you probably set up your service with IdentityServer incorrectly: you host IdentityServer that issues that bearer token along with API that uses that token for authorizing user.

There is a [StackOverflow topic](https://stackoverflow.com/questions/42450840/user-registration-process-with-identityserver4) with good example of IS/API layers segregation.

**Comment by MrGroovy** [comment]
Thanks for the reply. It is true that there are other endpoints in the same project. Those endpoints only relate to user management. There are also other services that are protected via the bearer tokens created by Identity Server.

Is it bad to have other endpoints in the same service as Identity Server? (In this case user management endpoints). What is the worst that can happen? Is it insecure?

**Comment by thePmr** [comment]
I don't see anything _bad_ in co-hosting user-management endpoints with IS. Moreover official IS docs [says the same](http://docs.identityserver.io/en/release/topics/add_apis.html), so frankly I don't quite understand [this comment](https://github.com/IdentityServer/IdentityServer4/issues/2846#issuecomment-448217116). May be something else was meant. And all other APIs (not related to user management) _better_ to be split away -  for architecture reasons, not security.

Back to initial error message: for us message disappeared after we stop using Bearer scheme (`IdentityServerAuthenticationDefaults.AuthenticationScheme`) as default one for authentication. Instead of this:
```
services.AddAuthentication(o =>
                {
                    // warning arose with that default scheme
                    o.DefaultScheme = IdentityServerAuthenticationDefaults.AuthenticationScheme;  
                    o.DefaultAuthenticateScheme = IdentityServerAuthenticationDefaults.AuthenticationScheme;
                })
                .AddIdentityServerAuthentication(options => ... )
```
 we did what [docs mentioned above](http://docs.identityserver.io/en/release/topics/add_apis.html) says:
```
services.AddAuthentication()
        .AddIdentityServerAuthentication(options => ... )
```

And for controller methods that should be protected with bearer token we add auth scheme to `[Authorization]` attribute:
`[Authorize(AuthenticationSchemes = IdentityServerAuthenticationDefaults.AuthenticationScheme)]`

**Comment by leastprivilege** [comment]
What @thePmr says. Bearer just doesn't make sense as a default scheme in an application that uses IdentityServer.
