### ISSUE TITLE
Checksession IFrame does not return "changed" when RefreshSignInAsync() was called

### ISSUE THREAD

**Issue by NilsEngelbach** [IdentityServer/IdentityServer4#2935]
I wanted to notify applications about changes to the user profile (profile picture, username...) using the checksession iframe.
The checksession iframe works fine when user signs out / different user signs it, but is not updated when doing changes to the profile.

```
        public async Task<IActionResult> OnPostAsync()
        {
            ...
            await UpdateUser(user);
            await _signInManager.RefreshSignInAsync(user);
            ...
        }
```

I can see that the actual asp net core session cookie changes after this but the cookie that is used for checksession stays unchanged.

I tried to figure out where and how this cookie is set, but i did not really get it.
Do you agree that the checksession cookie should also change?
And can you give me some hints how to fix this?

https://github.com/IdentityServer/IdentityServer4/blob/63a50d7838af25896fbf836ea4e4f37b5e179cd8/src/Services/Default/DefaultUserSession.cs#L168

**Comment by NilsEngelbach** [comment]
Okay, so I have to manually call it after `await _signInManager.RefreshSignInAsync(user);`, or extend the function to do the call?

**Comment by brockallen** [comment]
I was asking if you could check the user's `sid` claim in the cookie after calling that -- does it change?

**Comment by NilsEngelbach** [comment]
The session id was not changed.
As far as i see the `signInManager.RefreshSignIn()` calls `signInManager.SignIn()` which calls `userSession.CreateSessionIdAsync` but because the **session id was not changed** the checksession cookie is not updated. But I think it is intended that the session id is not changed, because `RefreshSignIn()` takes the `AuthenticationProperties` (and therefore the current session id) from `HTTPContext`.

https://github.com/aspnet/AspNetCore/blob/0f9ad16b096ca2535d77efd2ad27645449421b44/src/Identity/src/Identity/SignInManager.cs#L161

Do you think it is wrong if `RegreshSignIn()` creates a new Session ID, should i ask this question to the asp net core team?

**Comment by brockallen** [comment]
The session id is something IdentityServer creates (not ASP.NET Core). I asked you to check because I had forgotten how ASP.NET Identity handled that, but I guess it's just re-issuing the cookie for the same user, so I it makes sense that the `sid` doesn't change. 

So, the short of it is that the `sid` represents the current user session. Updating the cookie doesn't necessarily mean the session has changed. Using this to indicate to your client apps that some user data has changed may or may not be the right use of it (I think it's bit of a stretch).

You could issue a new `sid` by putting `"session_id"` into the `AuthenticationProperties`' `Items` collection when you call `SignInAsync`.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
