### ISSUE TITLE
Move IOperationalStoreNotification outside of EntityFramework.Storage

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer4#3116]
There's nothing EF related about it and seems it should be at ```Storage``` level, not ```EntityFramework.Storage```.

**Comment by brockallen** [comment]
It's used by the token cleanup service.

**Comment by Peperud** [comment]
Right, but why have the interface definition in EntityFramework.Storage? Token cleanup should happen for non-EF backed storage also and perhaps it makes sense not to have to copy/reinvent the interface.

**Comment by brockallen** [comment]
Ah, I now see what you're saying. Yea, ok, good point.

**Comment by UmutComlekci** [comment]
`IOperationalStoreNotification` have a depedency with `PersistedGrant`. So when I take out the `IOperationalStoreNotification` to `Storage` project; I need to take out `PersistedGrant` too and I think, it's not a good option. What we gonna do about this? Maybe we can take out Entities to `Storage` project too, because they aren't have dependency with EntityFramework neither.

**Comment by brockallen** [comment]
Ok, so I finally got around to sitting down to sort thru this. Since the main purpose of the `IOperationalStoreNotification` is to be used from the EF-specific `TokenCleanupService` then I don't see any reason to move it. No one else uses `IOperationalStoreNotification` and if you had other non-EF based implementations then you could invent your own notification there. Sorry.
