### ISSUE TITLE
InvalidOperationException: only a single identity supported

### ISSUE THREAD

**Issue by ghost** [IdentityServer/IdentityServer4#3197]
The following method from IdentityServerAuthenticationService.cs  prevents the use of mulitple identities by throwing a InvalidOperationException

        private void AssertRequiredClaims(ClaimsPrincipal principal)
        {
            // for now, we don't allow more than one identity in the principal/cookie
            if (principal.Identities.Count() != 1) throw new InvalidOperationException("only a single identity supported");
            if (principal.FindFirst(JwtClaimTypes.Subject) == null) throw new InvalidOperationException("sub claim is missing");
        }

  This is a pain because I am adding an additional identity through the IClaimsTramsformation, which is causes the exception to be thrown.  I could add into the current identity but having a seperate identity makes more sense. 

Why only allow for one identity?
The comment suggest this is only temporary, when will it be removed?
What is the best way around this?

**Comment by TomCJones** [comment]
Interesting question. If by principal you mean the guy that owns the process that has access rights and responsibilities, then it makes sense that there can be only one principal. If you have some other definition then that is less important. From a security perspective, I believe that there should be only a single principal, see https://tcwiki.azurewebsites.net/index.php?title=Principal#Context

**Comment by wilson0007** [comment]
Clearly you have no idea what I am talking about. 
A principal or ClaimsPrincipal is a default .net object from the System.Security.Claims namespace used for storing user information in a list of identies and claims.  Only one can exist at a time and is created by the authentication middleware, so your comment regarding multiple principals doesn't even make sense.


My question has nothing to do with multiple principals.  It has to do with multiple Identities. Identities are stored as a list in the claimsprincipal.  It is perfectly acceptable to have multiple Identities attached to one principal.  I shouldn't have to tell you this.

The problem is, your code (above) restrcts the usage of multiple Identities at time of authentication.

My question is why. Why allow only on IDENTITY,  especially when you have a comment that this is temporary.

**Comment by wilson0007** [comment]
Ya still there Tom?

**Comment by leastprivilege** [comment]
You can't really expect any more help here, do you?

https://github.com/IdentityServer/IdentityServer4/issues/2059#issuecomment-485923688

**Comment by wilson0007** [comment]
I guess not.  This is what I am talking about though. It is a pretty clear question horribly misunderstood.

**Comment by brockallen** [comment]
To answer your original question, yes we added the restriction and there was a reason. I don't recall what it was.

To answer your apparent sense of entitlement, I didn't reply because I hadn't had the time to research it and remember the reason. So now I'm torn -- either I answer too fast and I'm doing it wrong (as per the other thread), or I don't answer fast enough and I'm doing it wrong (as per this thread).

I don't know where you get your expectations from, but I'm fed up with it here.

**Comment by wilson0007** [comment]
I think you are being a bit sensative over a simple bump of a thread.

**Comment by brockallen** [comment]
Your behavior is different than a "simple bump of a thread".

**Comment by wilson0007** [comment]
I am sorry, but from my experience you guys just blatently do not read questions very well and it is frustrating being stuck with no support.  I did apologize for the way I handled it.  You guys do not deserve that at all.  You write good software for free and I appreciate that.  All I ask is you take the extra 2 minutes to really understand what people are asking, other what is the point of responding.

**Comment by brockallen** [comment]
Ah, finally a constrictive piece of feedback. I appreciate that. I agree, I could do a better job when I read and reply to questions. I know this is a weak point. But as I said before, this is effort is during my free time, and you get what you pay for. We have a paid support model, and if you use it then I guarantee you will get the level of attention you're seeking.

As for the free support here, as I tried to explain elsewhere, it's time consuming to respond to the level you ask. Each issue might take several minutes to read and try to understand the question. Often pages of code are dumped, and we're asked to parse and mentally compile to see if it's correct. And we get many of these per day, week, month, and year(s). So then it doesn't help when someone gallivants in making demands and passive aggressive complaints. 

So that's why we push back, otherwise I'd just being doing free work for your company and everyone else's and that's not how business works. So if you're working for a company and you need support, get your company to pay for it. Complain to them that they don't understand they need to pay for services. That's how business works. OSS is not free.

**Comment by wilson0007** [comment]
Fair enough.

**Comment by LindaLawton** [comment]
> We have a paid support model, and if you use it then I guarantee you will get the level of attention you're seeking.

I have used this and can vouch its value.  I was treated in a very  professional manner.  I also got quick responses even though i knew they were traveling.   I saved a lot of my time using this model.   I would suggest you consider it.  If you cant afford it i recommend [Stack overflow](https://stackoverflow.com/questions/tagged/identityserver4) where you can also get **free** help from a lot of people like you who use this system.
