### ISSUE TITLE
Template / documentation bug

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#3211]
### Issue / Steps to reproduce the problem

The template [Config.cs#L14](https://github.com/IdentityServer/IdentityServer4.Templates/blob/dev/src/IdentityServer4Empty/Config.cs#L14) creates a new solution with 

    return new IdentityResource[]
            {
                new IdentityResources.OpenId()
            };

While the quick start that uses it [1_client_credentials.rst](https://github.com/IdentityServer/IdentityServer4/blob/master/docs/quickstarts/1_client_credentials.rst) says 

     return new List<ApiResource>

I am in the process of updating the quickstart but in this instance I feel that the quickstart is correct and we should consider changing the template from  `IdentityResource[]` to new `List<ApiResource>`

Same goes for [Config.cs#L27](https://github.com/IdentityServer/IdentityServer4.Templates/blob/dev/src/IdentityServer4Empty/Config.cs#L27)

As always happy to submit a PR for the template fix.

**Comment by brockallen** [comment]
I don't know why we use List to be honest. It's not ever being modified in any way.

**Comment by LindaLawton** [comment]
So what's wrong then the tutorial?   I can deal with that

**Comment by brockallen** [comment]
Yea, I'm not sure there an issue here at all. Personally I don't care if one says List and the other returns IEnumerable or array.

**Comment by brockallen** [comment]
So wait, why did you open this issue in the first place? :)

**Comment by LindaLawton** [comment]
Because I like consistency.   

If the temple you say to use in the quick start says to use array and the quick start itself says to use list you are potentially going to confuse people.

I thought the template was wrong but after seeing your comment I suspect that it's the quick start that should follow it means I will need to update the sample as well I suspect.   I will have to check that.

**Comment by brockallen** [comment]
Okies. PR away as you see fit :)

**Comment by LindaLawton** [comment]
I have two of the quick starts shined up already I am going to wait and do a main pr for them all when I am done.

I will go through the samples after.

**Comment by MChouinardIdea** [comment]
Hi,

I'm currently learning and testing IdentityServer4 in the prospect to use it in the refactoring of our applications.  I don't want to criticize or that you take badly my comment but I do believe that it a necessity.

I have a hard time actually because the code generated by the dotnet new template, the code in the tutorials and in the quick start do not concurs.

**Comment by brockallen** [comment]
> I have a hard time actually because the code generated by the dotnet new template, the code in the tutorials and in the quick start do not concurs.

The main reason we don't try to sync with the Microsoft templates is because they change so often and it's a lof of work for us to follow their template du jour. I will say that if you understand the ASP.NET Core programming model, then our templates should be understandable. Point being, one should understand their framework. Otherwise, how could one build anything security related?
