### ISSUE TITLE
Unable to inlcude user selected value into claim while login using aspnetidenty and hybrid client (response_type : id_token and code) in identity server 4

### ISSUE THREAD

**Issue by anilchaulagain25** [IdentityServer/IdentityServer4#3252]
We are trying to include the user selected custom claim into user(client) token. But in case of hybrid client and AspNetIdentity, user claim is automatically assigned from the store behind the scene in ['connect/authorize','connect/token','connect/userinfo'] and the claims we assigned during login were lost.
We were able to set the custom claim into the identity server token but were unable to set the user selected value in the client token.
How to resolve this problem, or it is the issue of identity server.
Thank you.

**Comment by leastprivilege** [comment]
> We were able to set the custom claim into the identity server token but were unable to set the user selected value in the client token.

Can you explain what that means?

**Comment by anilchaulagain25** [comment]
@leastprivilege Thank you for your response.
Explanation : We explicitly assigned the user selected value to claim during login. which is available in identity server claims but not present in client claims(token).
We are using hybrid flow for ASP.MVC core application and AspNetIdentity.

**Comment by Samyeak** [comment]
@anilchaulagain25 @leastprivilege I am also facing the same type of problem while implementing AspNetIdentity with grant type of hybrid with mvc client.
In my case, an user is redirected to a custom page after successful login where the user selects a value. This user input value is to be added as a custom claim to the token passed onto the mvc client. 
After I add the additional claim to the claims principal, I re-signed the user. The claims in the Identity Server shows the user input value whereas the claims in the mvc client shows the claim value from the UserStore(Sql Server in my case).

**Comment by TomCJones** [comment]
This is an interesting request - but it is not clear how it could be applied. First a question - is it assumed by @Samyeak and @anilchaulagain25  that the request for the claim is made during signin with the OP (the IdSvr4)? If so, what would the persistence of the claim be? Until the user was signed out of the OP? That would imply that any client that requested authentication after the claim was inserted would also get the claim?  That sounds like a disaster waiting to happen.

OTOH the claim could be inserted during consent, but that is problematic because the claim would not persist over (for example) reauth. It would make sense if the claim were passed to the client one-time and the client was responsible for persisting the claim.

I would certainly like to see claims from the user inserted, but I can't see how the IdSvr could handle that using OpenID Connect. Seems like something wholly new. It however, is consistent with JWT.

**Comment by leastprivilege** [comment]
> We explicitly assigned the user selected value to claim during login. which is available in identity server claims but not present in client claims(token)

I assume this means you put the claims into the sign-on session (when calling SignInAsync)? If yes - you have access to it in the profile service and can put it into your tokens.

**Comment by Samyeak** [comment]
@leastprivilege Thank you for your response. I was able to pass custom tokens to the mvc client on user sign-in using Profile Service.
