### ISSUE TITLE
AddDeveloperSigningCredentials throws exception

### ISSUE THREAD

**Issue by VladislavAntonyuk** [IdentityServer/IdentityServer4#3303]
System.MissingMethodException: 'Method not found: 'System.String IdentityModel.CryptoRandom.CreateUniqueId(Int32)'.'

Asp.Net Core 3.0 preview 5

```
services.AddIdentityServer()
                .AddDeveloperSigningCredential() <- throws exception

<PackageReference Include="IdentityServer4" Version="3.0.0-preview3.4" />
<PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.0-preview.2" />

**Comment by leastprivilege** [comment]
Why do you need the access token validation package? Remove it, clean and try again

**Comment by VladislavAntonyuk** [comment]
Removed, but it didn't help

**Comment by sandord** [comment]
I've got the same problem and I'm using the token access validation package as well. 

In my case, the exception is only thrown in my integration tests, not my web project although both use `AddDeveloperSigningCredential`. While there's only a package reference to `IdentityServer4.AccessTokenValidation` inside the web project, the tests project has it too because the tests project has a dependency on the web project.

**Comment by leastprivilege** [comment]
The previews are currently not compatible - 

use IdentityServer latest only together with access token validation 2.7.

Also - using both packages in the same host is generally not recommended. Use this instead:

https://identityserver4.readthedocs.io/en/latest/topics/add_apis.html
