### ISSUE TITLE
Token is removed from persisted Grant Store

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3354]
Hi,

If access token (reference token) is expired then the access token details are deleted automatically when user use access token after token expired.

I wanted to keep this token details some where for audit purpose can you please advise on this.

Similarly, If there is any issue in access token request using auth. code then auth code details is removed from persistedgrants. 

Please asist us, how to keep those details somewhere for audit purpose?

**Comment by leastprivilege** [comment]
This might not be possible right now. We'll have a look.

**Comment by tssidhu** [comment]
Seeing a rather similar issue, but in this case I am noticing the following flow:

- User logs in
- Token is generated and saved in store
- User gets routed to redirectUri for calling client (signin-oidc in my case)
- Token is acquired from the store
- **Delete token request is triggered**
- User calls token endpoint using authorization_code flow, but since the entry was removed from Store, the token endpoint responds bad request

One way I have been able to get around this is by not performing any action inside the RemoveAsync(...) method of my implementation of IPersistedGrantStore. Not a good practice as this will continue to increase our store size without any cleanup. Any idea why the Delete token request is being triggered on user login?

**Comment by tssidhu** [comment]
I downloaded the source code for IdentityServer and found the culprit. So turns out the delete token request is triggered by the `await _authorizationCodeStore.RemoveAuthorizationCodeAsync(code);` call in `ValidateAuthorizationCodeRequestAsync` method of `TokenValidatorRequest.cs` class. Is there a reason we are removing the auth code after validation succeeds?

**Comment by leastprivilege** [comment]
Authorization codes must have one time only use semantics.

**Comment by brockallen** [comment]
How long would you want it kept around (for audit)? What's your audit process?

**Comment by leastprivilege** [comment]
Maybe in the future we should only set a flag - and not delete the codes/tokens etc. The cleanup could take care (if wanted) to delete them.

**Comment by tssidhu** [comment]
@leastprivilege Your explanation about token usage is correct. I was testing the generated tokens in incorrect manner and that's why seeing unexpected results. I think it's a good practice to clean up tokens after they are used. I'll leave the feature request decision to you guys, but I can easily implement the soft delete in my implementation of persistent grant store. So it's not blocking me in any way.

**Comment by brockallen** [comment]
This would involve adding a duration to the cleanup options. Also, with the new consumedtime field, the cleanup needs to perhaps use that as well?

**Comment by brockallen** [comment]
Do we want a `DeletedTime` in addition to the new `ConsumedTime` @leastprivilege?

**Comment by brockallen** [comment]
Given that we now have a `ConsumedTime` we no longer will be deleting them. The only code that deletes them is the `TokenCleanupService` and if you don't want that, then don't enable it. That way you can have your audit data, and then cleanup when you want. So in short, we don't need to do anything more for this.
