### ISSUE TITLE
[Sample Projects] Navigate to login while you logged in

### ISSUE THREAD

**Issue by Simusharp** [IdentityServer/IdentityServer4#3460]
Hi,
I was playing with sample projects (Quick start 8) and I noticed a behavior the might need to be addressed.

If I navigate to localhost:5000/Account/Login and enter Alice's credentials, I successfully login and redirected to home page. Now, if I navigate back to the login page, it asks about user name and password again while showing I am logged in the nav bar as in the attached picture.
![image](https://user-images.githubusercontent.com/50286240/61646607-db28bd80-ac67-11e9-845e-e552be78ecc0.png)

I think user shouldn't be allowed to navigate to login page if he/she already logged in.

**Comment by brockallen** [comment]
why not?

**Comment by Simusharp** [comment]
Well, I can make the case for GitHub website. If you try to navigate to https://github.com/login while you logged in, it will automatically redirect you to home page. I believe this is the common behavior for most of the websites.

**Comment by leastprivilege** [comment]
Are you saying that our samples should behave like this?

**Comment by Simusharp** [comment]
Yes, I think this will be better. Actually, I can create a PR. My line of thought is editing https://github.com/IdentityServer/IdentityServer4/blob/94ee1947c721723e8aa8272c35335f4819546ea1/samples/Quickstarts/8_AspNetIdentity/src/IdentityServerAspNetIdentity/Quickstart/Account/AccountController.cs#L56

A pseudo-code will be:
if the user is authenticated
     redirect to return url or home page

**Comment by brockallen** [comment]
Do the samples work for you?

**Comment by Simusharp** [comment]
@brockallen, Sorry, I don't understand your question. Do you mean current version of the samples? yes, it works for me but I am proposing a change.

**Comment by Jehoel** [comment]
> I think user shouldn't be allowed to navigate to login page if he/she already logged in.

I'm going to side with @Simusharp on this. I'd wager most users don't expect to be able to login if they're already logged-in. In my mind at least, it makes me wonder if it's to allow me to sign-in as another user while keeping my own claims in the `Actor` identity or otherwise make use of some impersonation functionality.

It's also unclear if using the login form while I'm logged-in will *replace* all of my session/identity cookies and claims or append to them.

just testing this now in some other widely used websites, e.g. phpBB and GitHub.com/login, when I make a `GET` request in my browser I get a HTTP 3xx redirection to my home-page in that web-app - so I'd definitely say this IS4 demo/sample is going against what I imagine most users' expectations are.

**Comment by leastprivilege** [comment]
Well - I think what you are describing is all valid application logic. It's not the job of a sample UI to implement app specific logic...
