### ISSUE TITLE
Add option to prevent automatic lower-casing of Issuer url

### ISSUE THREAD

**Issue by redoz** [IdentityServer/IdentityServer4#3600]
**Is your feature request related to a problem? Please describe.**
I just got bit by #1501 "HttpContextExtensions.GetIdentityServerIssuerUri lower case the URL. "

As this was resolved as an as-designed I'd like to propose either a hook to generate the URL on demand (as you need the context of the current request to do it, it isn't always possible to simply set it in the options), or simple bool option to let us disable this behavior.

**Comment by redoz** [comment]
Would you accept PRs for this? If so, would you prefer:
* `bool PreserveIssuerUriCasing` option. (default false)
* `Func<Context, Uri> CreateIssuerUri` option. (default null)
* `Func<Uri, Uri> TransformIssuerUri` option (default null)
* Something else?

**Comment by brockallen** [comment]
I guess we should have asked why you're asking for this?

**Comment by redoz** [comment]
Because our URLs are case-sensitive and having identityserver automatically lower-case the issuer uri breaks things.

**Comment by brockallen** [comment]
Just so you know, I think we did this because a developer in a client could configure one casing for the authority, and get back access tokens with the issuer with one casing. Then an API developer could set authority to be a different casing, and then the access token would fail validation because the issuers don't match.

The flag you're proposing would then put the onus on all the client and API developers to use the exact same casing for the authority config.

**Comment by brockallen** [comment]
Please have a look at the PR and let us know.

**Comment by brockallen** [comment]
@redoz ping -- please have a look.

**Comment by redoz** [comment]
@brockallen Sorry about that, I started writing a reply the other day and got distracted and forgot.

> The flag you're proposing would then put the onus on all the client and API developers to use the exact same casing for the authority config.

Yeah I think that's fair.

I looked over the PR and it looks good to me, I did however notice a typo and put a comment on it.

**Comment by leastprivilege** [comment]
discussion continues on PR
