### ISSUE TITLE
Ready to use production sample

### ISSUE THREAD

**Issue by noufionline** [IdentityServer/IdentityServer4#376]
Has anyone created a ready to use production sample of identity server?

With some guidelines and best practices.

That would be a great help for newbies like me.

**Comment by prabhakarreddy1234** [comment]
I found this useful.   [https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore](url)

**Comment by noufionline** [comment]
@prabhakarreddy1234 link not working

**Comment by prabhakarreddy1234** [comment]
try this.    https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore

**Comment by aligin** [comment]
Hey, we are using TwentyTwenty.IdentityServer4.EntityFrameworkCore since May 2016. And our custom IProfileService EntityFramework realization.
We've implemented some custom classes:
public class MonqCustomTokenValidator : DefaultCustomTokenValidator
public class UserProfileServiceExtended : UserProfileService

Mostly we are using Implicit flow with id token for ASP.NET MVC authorization (this project secures basic htmls and other file resources for SPA application and doesn't call apis) and OAuth token for Gateway (and other) API services.

**Comment by Lutando** [comment]
Also, the signing certificate, should be stored and retrieved from some sort of certificate store or key vault. It should not be bundled within the solution/application.

**Comment by leastprivilege** [comment]
Keep in mind we are still in pre-release. Whatever you come up with - we might change something before RTM

**Comment by brockallen** [comment]
Closing -- we'll have more docs/samples as we get closer to RTM.

**Comment by lineker** [comment]
any news on this ?
