### ISSUE TITLE
Support for windows authnetication

### ISSUE THREAD

**Issue by venkatrv** [IdentityServer/IdentityServer4#38]
Can IdentityServer4 takes Windows credentials and convert to IdetityServer4 token?

**Comment by lazyspark** [comment]
@venkatrv Seems like you are coming new into Identity Server and starting with Identity server 4. I am not sure if that is great idea because currently all of this is getting formalized. Please check out this podcast on .NET Rocks show https://www.dotnetrocks.com/default.aspx?ShowNum=863 where Dominick talks about the current state of the project. 

That being said you can use Identity server 3 and there is an example of Windows Auth in there. I am no owner of this repo or related to this project :) but just my cents to help you. 

Identity server 3 Windows Auth Example - https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/WebHost%20(Windows%20Auth)

**Comment by venkatrv** [comment]
Thank you @lazyspark. Yes, you are right. I am new to IdentityServer and thought picking up the IdentityServer4 is better, because the previous one (IdentityServer3) is using old technology and MS may not invest in that technology anymore (I read these comments in the forum).
But you are right, IdentityServer4 may not be completely ready yet.
Ok, I will step back and dig into IdentityServer3. I am also looking for trusting one identity server with another  and my problem is to pass the token across windows domains. I hope this can be achieved by using Identity Server.

**Comment by LiveLikeLastDay** [comment]
IdentityServer4 released 1.0.0, is there any news regarding Windows Authentication?
