### ISSUE TITLE
CorsPolicyProvider and AllowCredentials

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer4#3816]
This has been discussed before, but I choose to open another one as I haven't found the same premise on the previous items.

So the easiest way to start is by looking at the excellent POC by @karpikpl. I've taken it a bit further, but the basics are (with made up host names):
- IdSrv4 running on http://id4:5000/
- SPA login UI running on http://spa:8082
- client app running on http://client

Given that the client is correctly configured and the authorize request validates, I end up on the SPA ui login as expected. 

IdSrv4 app has an AuthenticateController route at /api/authenticate that is there to support the SPA login UI which will do something like this:
```
        // call the API
        const response = await fetch('http://id4:5000/api/authenticate', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          credentials: 'include',
          body: JSON.stringify({
            username,
            password,
            returnUrl
          })
        });

```
Now, for this to work, I need to add `options.Cors.CorsPaths.Add(new PathString("/api/authenticate"));` to `IdentityServerOptions` at startup, otherwise IdSrv4 says "CORS request made for path: /api/authenticate from origin: http://spa:8082 but was ignored because path was not for an allowed IdentityServer CORS endpoint".

But when I add the route to CorsPaths, the code will go through the CorsPolicyProvider and as the ACAC is not set, the pre-flight will no longer work.

To me, it looks like there should be a way to add this header to the CorsPolicyProvider. Of course, if there are alternative solutions, then I'm all ears.

The attempt below was also futile, as it never gets that far.
```
            var cors = new DefaultCorsPolicyService(new LoggerFactory().CreateLogger<DefaultCorsPolicyService>())
            {
                AllowAll = true
            };
            services.AddSingleton<ICorsPolicyService>(cors);
```

**Comment by karpikpl** [comment]
Hey,
I'm not really sure I got the issue right, but one thing that helped me when working with IS4 is that there are actually 2 CORS settings there.
One is for IS4, that's the `DefaultCorsPolicyService` bit and the other one is for any other controller that you add to the project.
That's because IS4 is hooked into ASP .NET on a lower level as middleware.

I have it here: https://github.com/karpikpl/identity-server4-with-SPA-UI/blob/master/id4/src/IdentityServer/Startup.cs

In that file CORS settings are in 3 different places:
1. [CORS for custom controllers](https://github.com/karpikpl/identity-server4-with-SPA-UI/blob/f3e76e88298ca22fd9a65de8f42eb2a726649b71/id4/src/IdentityServer/Startup.cs#L30)
2. [CORS for IS4](https://github.com/karpikpl/identity-server4-with-SPA-UI/blob/f3e76e88298ca22fd9a65de8f42eb2a726649b71/id4/src/IdentityServer/Startup.cs#L70)
3. [Register 1) - CORS for custom controllers, in the ASP](https://github.com/karpikpl/identity-server4-with-SPA-UI/blob/f3e76e88298ca22fd9a65de8f42eb2a726649b71/id4/src/IdentityServer/Startup.cs#L90)

If you have a sample somewhere I can take a look too :)

**Comment by snothub** [comment]
> 
> If you have a sample somewhere I can take a look too :)

Thanks. It's really just a fork of your repo updated to netcoreapp3.0 and changed host names, feel free to have a look. As mentioned earlier, the spa login does a post to /api/authenticate and IdSrv4 console just outputs
`CORS request made for path: /api/authenticate from origin: http://ipv4.fiddler:8082 but was ignored because path was not for an allowed IdentityServer CORS endpoint`

https://github.com/snothub/identity-server4-with-SPA-UI

**Comment by karpikpl** [comment]
Hey,
I've migrated my sample to 3.0 - take a look https://github.com/karpikpl/identity-server4-with-SPA-UI/pull/1

sometimes CORS errors are false positives, maybe check if you can hit that endpoint with curl or something that ignores CORS
