### ISSUE TITLE
An elevation of privilege vulnerability exists when the ASP.NET Core fails to properly sanitize web requests.

### ISSUE THREAD

**Issue by medidimurali** [IdentityServer/IdentityServer4#3819]
Hello,

Can you check and help us resolve the following issue with Identity Server 4;
ISSUE:
Security Issue when doing deep scan using jfrog xray;
An elevation of privilege vulnerability exists when the ASP.NET Core fails to properly sanitize web requests.
Package Type : Nuget
Type : Security
Provider : JFrog
Summary:
An elevation of privilege vulnerability exists when the ASP.NET Core fails to properly sanitize web requests.
Severity : High
Created : Feb 6, 2018 8:21:25 AM
CVEs : CVE-2017-0249 (CVSS v2 Score : 7.5/CVSS:2.0/AV:N/AC:L/Au:N/C:P/I:P/A:P) (CVSS v3 Score : 7.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L)
Versions : 4.0.0-beta-22416 ≤ Version ≤ 4.0.0
4.3.0-preview1-24530-04 ≤ Version ≤ 4.3.0
References
https://github.com/aspnet/Announcements/issues/239
Modified : Oct 2, 2018 7:29:28 AM
Edited : Oct 4, 2018 10:54:38 AM

![Capture](https://user-images.githubusercontent.com/37628953/68718250-488d9080-056e-11ea-91fd-ca8c4685c6f8.PNG)

**Comment by leastprivilege** [comment]
You are probably not familiar with the "responsible disclosure" process in security - let me explain.

Our repo has a [security.md](https://github.com/IdentityServer/IdentityServer4/blob/master/SECURITY.MD) file, which details how reporting "security vulnerabilities" works - you also must have seen the corresponding button when you opened the issue:

![image](https://user-images.githubusercontent.com/1454075/68740477-72d16380-05eb-11ea-996b-93df750541bd.png)

(the last option)

I know you additionally also send an email afterwards - but since we are here - let's have a look.

The report you are sending me is for a fixed and old (2017) vulnerability in ASP.NET Core - how is this related to our code? If you are running a very old ASP.NET Core application that is affected by this security bug - please use the steps described in Microsoft's document to upgrade.

https://github.com/aspnet/Announcements/issues/239
