### ISSUE TITLE
No DbContext named 'PersistedGrantDbContext' was found in dotnet core 3.1

### ISSUE THREAD

**Issue by fuhongbo** [IdentityServer/IdentityServer4#3942]
When i run dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb. I get the error message like "No DbContext named 'PersistedGrantDbContext' was found" in dotnet core 3.1. How to solve it？thanks

**Comment by breynolds** [comment]
I'm getting the same issue, so I'm stuck in the entity framework portion of the IdentityServer tutorial.

**Comment by 7w0** [comment]
Did you do the "[Configuring the Stores](http://docs.identityserver.io/en/latest/quickstarts/5_entityframework.html#configuring-the-stores)" step? I'm not sure why that's necessary, but I spent about 20 minutes trying various things to fix this error. Once I did that step, it worked.

**Comment by firstdivision** [comment]
For anyone else still confused about this while trying to go through the quick starts @7w0  had it right, but when I got to that part of the tutorial I somehow ended up with two calls to `AddIdentityServer` in my `Startup.cs` (probably because I skipped the Javascript lesson).  anyway, once I matched mine to the one in https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Quickstarts/5_EntityFramework/src/IdentityServer/Startup.cs I was back on track.
