### ISSUE TITLE
"scp" versus "scope" and RFC 8693

### ISSUE THREAD

**Issue by jasonmac01** [IdentityServer/IdentityServer4#4030]
It appears that IdentityServer is producing access tokens with a claim of "scope" with the value as an array of strings.

[RFC 8693](https://www.rfc-editor.org/rfc/rfc8693.html#name-scope-scopes-claim) defines this claim to be a space-separated string. This is causing issues with some platforms who consume JWTs and align with the specification's definitinon of the claim.

1. Is this output interface configurable?
1. Is IdentityServer considering a switch to more closely align with the RFC?

**Comment by leastprivilege** [comment]
Well - this RFC is a standard since 2 or 3 weeks. We are using the scope claim since a couple of years. Access token content is not defined in OAuth at all.

You can change the type by override the default token service.

**Comment by jasonmac01** [comment]
Right, but [this](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-19) was the draft that RFC 8693 ultimately finalized. If you look at the revisions, you'll see:

  - [v1 - v12]: The scopes should be in an `scp` claim, defined as an array of strings.
  - [v13+]: Since April 2018, the draft spec and the RFC state that the claim should be called `scope` as a space-delimited string.

It appears that IdentityServer is at the intersection, of sorts - a `scope` claim that is modeled as an array of strings.

I'm representing Amazon API Gateway. We recently launched support for JWT authorization, and we noticed some of our customers are using your software as their IDP. Great! But, I just want to make sure these folks have an easy way to shift into alignment with the RFC in regards to this property.

  - Would you be able to share an example of how to configure this? 
  - Would you consider mentioning this in your documentation?

**Comment by leastprivilege** [comment]
I don't really want to start that discussion - but the RFC you are using as reference is NOT the authoritative source how an access token should look like (there is none).

If you are building an API gateway that needs to be able to consume access tokens from various vendors, be prepared to see all kinds of variations (including complete absence of a scope concept). The reason for this is because no standard exists.

I would recommend you become more flexible with your JWT parsing.

That being said - I can have a look how much work it is to change the scope format and add a note to our docs.

**Comment by leastprivilege** [comment]
IdentityServer v4 conforms now to the JWT profile for access tokens - which is the right spec to look at (and not the token exchange one).

https://leastprivilege.com/2020/06/15/the-jwt-profile-for-oauth-2-0-access-tokens-and-identityserver/
