### ISSUE TITLE
Load A X509 Certificate Inside An Asp.Net Core Application Running In A Docker Container

### ISSUE THREAD

**Issue by raholland79** [IdentityServer/IdentityServer4#4256]
I realize this isn't the place to ask but, I've been messing with this for a few days now.

I can't work out how to generate and manage the signing certificate for my IS4 server inside a docker container orchestrated by Kubernetes?

I guess I could generate it on my laptop and put it in the containers filesystem?  Maybe something like cert-manager?

If I can get beyond this I can finally deploy!

**Comment by vadimdr** [comment]
The easiest way for us was to map the certificate file as a `volume` inside the docker container and load the certificate during the startup. When we have loaded the certificate, we have also moved it to our DB, so the next start of the server will take the certificate from the DB instead of the docker volume. It will also allow you to implement certificate rollover feature (you can create a local API with action to upload a new validation certificate and an action to promote the validation certificate to become a signing certificate)

**Comment by raholland79** [comment]
Great information - I think that is enough to go on
