### ISSUE TITLE
Checksession is not sending the cookies to the identity server, 

### ISSUE THREAD

**Issue by muralisambu** [IdentityServer/IdentityServer4#4264]
Hi,

tried multiple times, check session is not able to send the cookies after logged in and the application is logged out. 
checked multiple sites to change the cookie samesite attribute to none, Cookiesecurepolicy to always(secure) but still no luck.

Identity server4 2.2.0 and aspnetcore 2.0.3
![image](https://user-images.githubusercontent.com/26081686/78886975-ba65f980-7a7c-11ea-9637-f9eceed51879.png)

**Comment by leastprivilege** [comment]
Well - this looks like a SameSeit cookie issue. Also keep in mind that we can only support the latest IdentityServer/ASP.NET Core versions.

Generally speaking - check session will not work reliably anymore.

https://leastprivilege.com/2020/03/31/spas-are-dead/

**Comment by muralisambu** [comment]
@leastprivilege  Thanks for the response, if I upgrade to latest identity server 3.1.2 and aspnet core to 3.1 will it work or do i need to do any changes to make it work?

**Comment by justincts1975** [comment]
> @leastprivilege Thanks for the response, if I upgrade to latest identity server 3.1.2 and aspnet core to 3.1 will it work or do i need to do any changes to make it work?

I'm not sure if we're talking about the same issue, but in order to get the Quickstart projects to work  today in 3.1, all I had to do to get it working was make everything HTTPS. I was really pissed off at first because the MVC to IdP Quickstart solution didn't work from the latest code in github, but then I realized it might have something to do with SameSite cookies and switched to HTTPS.  I would suggest the team retest and update those projects accordingly. 
Note that you can turn on and off those "SameSite" features in chrome (for testing purposes) here: chrome://flags/

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/host/Extensions/SameSiteHandlingExtensions.cs

**Comment by tai-yi** [comment]
After set right SameSite value, you may need check browser settings.

* Chrome
  settings -> privacy and security -> Site Settings -> Cookies and site data 

If `Block third-party cookies` is checked, please add you OP domain into Allow list

**Comment by leastprivilege** [comment]
> If Block third-party cookies is checked, please add you OP domain into Allow list

this setting will sooner or later become the default value for all browsers. The check session mechanism will not work reliably anymore if client and OP are cross-site.

https://leastprivilege.com/2020/03/31/spas-are-dead/
