### ISSUE TITLE
Silent Sign in

### ISSUE THREAD

**Issue by SVarasteh** [IdentityServer/IdentityServer4#4392]
### Question

Hi,
We are utilizing Identity Server 4 for authentication/authorization users in our application which is a react spa web app. The client flow is implicit. Now we need to change our registration flow so users were not required to login following registration.
I found this link : https://benfoster.io/blog/identity-server-post-registration-sign-in
it is related to Identity Server 3 and I am not sure if I can customize it for Identity Server 4.
I'd be thankful if you can guide me to choose a secure and suitable approach.

Thanks in advance,
Saeideh

### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by katlimruiz** [comment]
Isn't this just to have a token with a lot of space for expiration (180 days?) and then storing it in local storage?
Obviously you depend on the user not clearing its data, but is inevitable and part of the model.

**Comment by alexandis** [comment]
I'm also interested in silent sign-in implementation for IdentityServer4.
We have a custom setup allowing the same login name under different tenant. The tenants list is displayed as a dropdown on Angular app UI and we would like to re-login a user with the selected tenant instead of the user currently logged in. It needs to look like a simple page reload.
