### ISSUE TITLE
Identity Server 4 as a background service

### ISSUE THREAD

**Issue by granthoff1107** [IdentityServer/IdentityServer4#4540]
Sorry, this is a broad question but I'm writing it as a question/potential feature request,  I just want some feed back and thoughts on it.

I'm wondering if IdentityServer 4 could be run as a background service and whether that would be safe.

I've been switching back and forth on my project between using IdentityServer, and not.  I was just thinking it might be cool if Identity server could be run as a background application, and hosted in my current application.

There are a few benefits of it being hosted as a background service.    
I can deploy a single application and the token server is not dependent on my application code.
and It would be easy to move to another instance of Identity server if the logic wasn't integrated directly with the project I'm using.  

However I'm not sure how practical it would be, or whether there would be any security implications etc

**Comment by steelsteed** [comment]
ID4 server is framework for building an Identity server, however it heavily relies on use of .net core 3.1 as the underlying SDK.  While it is inherently written to be an asp.net web API, it could also be a console app, or a self hosted windows app, or even run on other OS like Linux, or Dockerized for easy portability.  There are lots of options.  I think you need to refine your requirements, and then see what you are comfortable with, because you will have to write code at some point to get a working solution.
