### ISSUE TITLE
Signout of Identity server doesn't invalidate the tokens

### ISSUE THREAD

**Issue by Aravind1729** [IdentityServer/IdentityServer4#4548]
### Question
Once I logout of identity server the access token issued still remain valid. Is this the intended way? Does the Identity server not automatically revoke the tokens once a user is logged out?
### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by wterpstra** [comment]
I assume you are using a self contained access token (like a JWT). In that case the access tokens are not being 'revoked' by IdentityServer. Self contained tokens mean that that all the claims (like expiration date) are stored in the token and the token is protected with a signature.

You can either keep the lifetime of your access token small and revoke the users refresh tokens when logging out or use [reference tokens](https://docs.identityserver.io/en/stable/topics/reference_tokens.html) instead of self contained access tokens.
