### ISSUE TITLE
Provide an option to change samesite mode for idsrv.session cookie

### ISSUE THREAD

**Issue by ahmedkapasi** [IdentityServer/IdentityServer4#4808]
There is no option to change samesite mode for idsrv.session cookie , I checked the code found that it has been hardcoded to always use as SameSiteMode.None mode which is breaking the application due to chrome recent updates

**Describe the solution you'd like**
Please provide some configuration property to change the mode for idsrv.session cookie samesite mode

**Comment by bryantlikes** [comment]
I think there is already a PR out there for this issue. https://github.com/IdentityServer/IdentityServer4/pull/4711

**Comment by garyevari** [comment]
I am suffering this same issue as well.

In case anyone else has been doing local dev of an instance running on HTTP, all of a sudden you will attempt to login and you will not get an idsrv cookie issued on redirect due to `This` Set-Cookie was blocked because it had the "SameSite=None" attribute but did not have the "Secure" attribute, which is required in order to use "SameSite=None"."`

I believe this is due to the code within Identity Server that helpfully changes the secure cookie flag based on whether it is running on HTTP or HTTPS now needs to be extended to match Chrome's new SameSite requirements.

However, I believe that might get messy when it comes to legacy browsers and Safari etc.

**Comment by brockallen** [comment]
We'll have a look at the PR when we can. The short term solution is to do all development over HTTPS.
