### ISSUE TITLE
Cleanup consumed refresh tokens

### ISSUE THREAD

**Issue by thomasfrisko** [IdentityServer/IdentityServer4#4859]
We would like to avoid storing consumed refresh tokens in the database for a long time since this will become a performance bottleneck, since our refresh token lives for 30 days while our access tokens lives for 75 minutes and we are using refresh token rotation. 

IdentityServer already has support for cleaning up refresh tokens that have expired, however, refresh tokens that are not expired but instead are consumed will not be removed from the database. As described here http://docs.identityserver.io/en/latest/topics/persisted_grants.html#refpersistedgrants the consumed refresh tokens can be used e.g. to detect suspicious activity. However, we would like to delete consumed refresh tokens from the database before they expire, if they have been consumed e.g. 24 hours ago or more.

We have looked at the source code for the `TokenCleanupHost` and `TokenCleanupService` and there does not seem to be an obvious way of extending/overriding the default functionality.      
The extension method `AddOperationalStore<TContext>` dependency injects `TokenCleanupHost`. Within `TokenCleanupHost` the `TokenCleanupService` is directly resolved through `ServiceProvider`. This means it is not possible to extend/override the implementation of `TokenCleanupService` and inject that instead.
I assume we have to disable the default implementation `options.EnableTokenCleanup = false;` and then provide our own implementation/override of `TokenCleanupService` and `TokenCleanupHost`.
Is this the intended way or do you recommend another way to achieve this?
Thanks!

**Comment by mcrio** [comment]
Few months passed since this issue came up, but for everyone else landing here, maybe you can just replace the default service already registered with your own implementation.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.extensions.servicecollectiondescriptorextensions.replace?view=dotnet-plat-ext-5.0#Microsoft_Extensions_DependencyInjection_Extensions_ServiceCollectionDescriptorExtensions_Replace_Microsoft_Extensions_DependencyInjection_IServiceCollection_Microsoft_Extensions_DependencyInjection_ServiceDescriptor_
