### ISSUE TITLE
Sample token/ticket cache example to avoid storing tokens in the cookie?

### ISSUE THREAD

**Issue by JoeMarkov** [IdentityServer/IdentityServer4#4943]
### Question

To keep the session cookie small, I wonder if there are some sample code available to store the received tokens in a database and cached in memory?  (perhaps using the IDistributedCache?)

Or what do you do to keep the session cookie compact?

**Comment by pablopioli** [comment]
Those are the options you have. Use a cookie to store the token on the client or cache it on the server. 
You need to balance the trade offs of each one and choose one dependending on you context.

To get to access token do

```
options.Events = new OpenIdConnectEvents
{
   OnTokenResponseReceived = context =>
      {
           var accessToken = context.TokenEndpointResponse.AccessToken;
           // Store the acess token in cache, you need to parse it to get the sub
           return Task.CompletedTask;
      },
};

// Don't store the tokens in the cookie
options.SaveTokens = false;
```

Now you need to get the sub of the user on each call and get to token from storage (memory, cache, database, etc.)

**Comment by JoeMarkov** [comment]
Thanks! Do you know if there are any ready made caching code to cache the tokens in a database for example? Don't feel like creating my own to avoid introducing new security holes. 

After I wrote my question I discovered the option to create my own SessionStore and cache the tokens there instead, like:

```
services.AddAuthentication("Cookies")
		.AddMyCookie(opt =>
		{
			opt.SessionStore = new MySessionStore();
		});
```

Any thoughts on that approach?

**Comment by pablopioli** [comment]
To store the token you need reversible encryption. So you can't use a hash. That's why is better use the cookie, the browser stores the cookie but can't decrypt it. The server has the decryption key but don't have the cookie value, permanently.

If you take the store the token in a database route you can use ASP.Net Core Data Protection, so you don't create your own crypto
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-3.1
