### ISSUE TITLE
so, you are not free any more?

### ISSUE THREAD

**Issue by nextfool** [IdentityServer/IdentityServer4#4953]
### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by jlopez788** [comment]
Looks like this version will stay free under their current license agreement, however all new development will be done on their new paid version. Security updates will be done on this code

**Comment by nenadvicentic** [comment]
My feeling is that they will stack Identity Server 5 with additional/business features to justify the price and it will become over bloated commercial product with features most of people that use IdentityServer4 don't need. It will become opposite of what made it so popular in the first place. Really bad move.

**Comment by Jonatthu** [comment]
There is many ways to monetize this project without the core becoming a paid version like building premium features outside the free environment just like Apollo or other open source frameworks, take a look on prisma as well

**Comment by leastprivilege** [comment]
This was not an easy decision - but we hope this is the best model going forward.

You can read about the long journey on my blog
https://leastprivilege.com/2020/10/01/the-future-of-identityserver/

We know that we cannot make everybody happy but we adjusted the licenses and also added discounts for startups and non profits. Also you can always reach out to us if you think the licensing does not work for you via
https://duendesoftware.com/contact

> will become over bloated commercial product
This is not the plan.

> At least, they should have went direction Elasticsearch guys did
no offense, but it is fascinating how many people suddenly get in touch with us to consult us about business models. If only a fraction of them would have supported us in the past, maybe we would have gone a different direction.

**Comment by nenadvicentic** [comment]
> no offense, but it is fascinating how many people suddenly get in touch with us to consult us about business models. If only a fraction of them would have supported us in the past, maybe we would have gone a different direction.

Firstly, I doubt that people that contact you via Github got in touch suddenly. I, for example, have been around here for 5 years (both `IdentityServer3` and `IdentityServer4`) and communicating. Secondly, It should not be surprise for you that so many people used IdentityServer, when it was open-source, backed by .NET Foundation and directly recommended by Microsoft (in their documentation and VS templates). That said, you have also done great work as creators of the product. I would think that this issues should have been solved between you guys and Microsoft.

Problem with this license model is that small businesses will get burned the most. Small business might have 50 users per one client license, while corporation might have a million. In addition, because product was open source for many years, in my case, we splitted what could have been 1 client website, into multiple clients (basically sub-domains) and now we'll have to pay the price for old decision. Nobody thought about minimizing number of clients.

Regarding Elasticsearch model, where core is free, you mentioned in the blog post you have tried it, but it did not work. Problem here is, you delegated add ons to 3rd parties and did not promote the model well  (first time I was aware of this was reading your blog post from last week). On the other side, Elastic is building add-ons in the house and everyone is completely aware of their business model.

Lastly, maybe it should have been better if we could have had public discussions before you have made final decision what to do with the IdentityServer. Perhaps better solution could have popped up.

**Comment by Jonatthu** [comment]
@leastprivilege I agree you guys should get paid for your awesome work, but 1500 dlls is too much for my startup, which I am the ONLY DEV and the ONLY "investor" meaning I have zero profit and zero investors right now, I have messaged you on your contact form to have some better deals ideas, and also I agree that everyone should had donate and supported this platform so you guys do not come to this conclusion, also microsoft should had invested more on this. If this will make sure IdentityServer open source keeps alive is okay by me.

**Comment by Jonatthu** [comment]
And for everyone else that is planning to add some hate to the decision, please just stop, keeping a project like this is really hard specially when nobody is paying you. Ether start donating right now until 2022 so the team changes mind or start paying for the premium way.

**Comment by leastprivilege** [comment]
...but to answer the question in the title of the issue.

"we" are still free. Nothing will change here 'til end of 2022. The new Duende IdentityServer will also stay open source - and also completely free for dev/testing as well as non-commercial open source projects.
