### ISSUE TITLE
Consider removing AllowAccessToAllScopes

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#499]

**Comment by brockallen** [comment]
done on config branch

**Comment by brockallen** [comment]
done

**Comment by liamdawson** [comment]
Is there an alternative to be used?

**Comment by leastprivilege** [comment]
Specify the scopes explicitly.

**Comment by ChristopherHaws** [comment]
I'm a bit confused by this. In the talk you gave at NDC (https://youtu.be/l7MgGY3lnts?t=30m59s) you mentioned that scope is no longer required  and that this is why the scope field on `RequestClientCredentialsAsync` is not a required field (hence the null default value). This is also mentioned in your blog (https://leastprivilege.com/2016/09/14/new-in-identityserver4-default-scopes/).

Is there a particular reason that this feature was removed? Perhaps a security risk of some sort?

Thanks!
Chris

**Comment by brockallen** [comment]
`scope` is not required as a parameter, but you still need to indicate which scopes the client is allowed access to via the `AllowedScopes`.

**Comment by ChristopherHaws** [comment]
@brockallen After looking through the code trying to figure out why I've been getting an `invalid_scope` error, I found that the reason was because I was using `AllowedGrantTypes = GrantTypes.ClientCredentials` and I had `AllowOfflineAccess = true`.

I then looked up the RFC and found this section which states that a refresh token should not be included:
https://tools.ietf.org/html/rfc6749#section-4.4.3

Just wanted to post this here for anyone else running into this issue. Perhaps in the future additional error messages could be included in the server logs to indicate that the client is configured in an invalid state.

Thanks!

**Comment by brockallen** [comment]
What was the error in the IdSvr logs for this misconfigured scenario?

**Comment by ChristopherHaws** [comment]
@brockallen After having read parts of the RFC, I guess the error isn't that bad, although it would be nice if the error happened earlier (at the time the client is configured) rather than during the actual client request... I just wasn't understand the error it until I did some digging into the RFC to understand what some of these terms meant. I think that the part that was tripping me up was that I needed to understand that `AllowOfflineAccess` means "allow the client to request a refresh token", which in turn doesn't make sense for the client credentials grant types. I am still fairly new to doing auth beyond using simple middleware for google/twitter/etc, so there are a lot of new terms that I am still trying to digest. :)

The error from the log:
```
IdentityServer4.Validation.TokenRequestValidator:Error: test-client cannot request a refresh token in client credentials flow
IdentityServer4.Validation.TokenRequestValidator:Error: {
  "ClientId": "test-client",
  "ClientName": "Test Client",
  "GrantType": "client_credentials",
  "Scopes": "test-scope",
  "Raw": {
    "grant_type": "client_credentials"
  }
}
```

**Comment by brockallen** [comment]
> IdentityServer4.Validation.TokenRequestValidator:Error: test-client cannot request a refresh token in client credentials flow

Yea, I am not sure how much more clear that can be. IdentityServer is not meant to absolve one from understanding the protocols :)
