### ISSUE TITLE
Do you have a plan to move .net 5

### ISSUE THREAD

**Issue by HaiyanDu7** [IdentityServer/IdentityServer4#5157]
Do you have a plan to move .net 5?

**Comment by leastprivilege** [comment]
IdentityServer4 works fine on .NET 5 since there were very few breaking changes between 3.1 and 5.

If you want to use a fully supported version that explicitly targets .NET 5, I recommend having a look at Duende IdentityServer v5
https://github.com/DuendeSoftware/IdentityServer

While the license has changed, there are still free versions available
https://duendesoftware.com/specialoffers
