### ISSUE TITLE
Logout without id token.

### ISSUE THREAD

**Issue by robert-pusswald** [IdentityServer/IdentityServer4#544]
Hi!

I'm using IdentityServer4 1.0.0-rc3. (I am a newbie :) )
As i see in the source code of the EndSessionRequestValidator (ValidateAsync), PostLogoutRedirectUri is only set in the ValidatedRequest if an idTokenHint is present.
We do not want to save Tokens in our client application. So - when i click on logout in our application, i do not have the PostLogoutRedirectUri in my logout action of the identityserver. (IIdentityServerInteractionService  - GetLogoutContextAsync)

I am aware that logout without the token maybe is a security risk. Is it really necessary to save the id token in my client application?

Thanks for your help

**Comment by leastprivilege** [comment]
Yes - you need the id token for doing the post logout redirect. See the spec.

**Comment by cwe1ss** [comment]
Hi Dominick, thx for your quick reply! I'd like to add a few things to my colleague's question:

Specifying the id_token_hint seems to be a [recommendation](https://openid.net/specs/openid-connect-session-1_0.html#RPLogout) but not a requirement. 

We use IdentityServer as an OAuth provider for our customer-facing website and for our app. We don't have any third party client apps.

Our main concern with storing the id_token is that - in our website - we would either have to store the id_token in a cookie (which is a no-go in my opinion because the value would be too big to send it with every request) or in a database. Since we don't need the it_token for anything after the login, storing it in a database also seems unnecessary. 

I understand that not providing the id_token means that someone could logout a user through some sorts of phishing link, however I don't see this as a big concern if the OAuth-provider is only used for our own applications. 

Also, there might be scenarios where we'd like to "play it safe" and do a logout redirect-loop through the identity server to make sure the user is logged out, even if he's not logged in on our website.

Let's say we store the id_token in a cookie. Unless we store our own auth token and the id_token in the same cookie, it can't be guaranteed that they will always both exist. Someone could delete the id_token cookie which will result in the post-logout-redirect-url no longer working.

Again, since we use IdentityServer just for our own applications, loosing the post logout redirect url seems like a big loss in these cases.

Thanks again for your help and the amazing work with this project!

**Comment by leastprivilege** [comment]
The concern is not logout phishing.

The concern is open redirector. If you send us a post logout redirect URL - how would we know it is legitimate? An attacker could craft logout URL that start at a trusted site, but end up on an attacker's site.

You are free to do whatever redirect you want to do yourself on the logout page. Would that work for you?

**Comment by cwe1ss** [comment]
Thanks again for your quick reply! We definitely want to have the post-logout redirect URL validated with the pre-registered URLs. The problem right now is just that this only happens if we also specify an id_token.

If we don't specify an id_token_hint, you just ignore the redirect_url - even if it's a pre-registered entry.

**Comment by cwe1ss** [comment]
PS: yes, doing a fixed redirect to our homepage would work right now since we only have one application. However we might have more applications in the future so it would be great to use the redirect_uri feature.

If I'm correct, validating the post_logout_redirect_uri without an id_token_hint would mean, that you would have to validate the URI against all redirect_uris of all registered clients since the logout endpoint has no other way to identify the calling application. In other words, RP 1 could probably specify a redirect_uri of RP 2 but it could not specify a completely unknown URI. 

While I agree that this isn't great, it doesn't seem like a big issue - especially in cases where IdSrv is used exclusively within the boundaries of one company. 

Do you see this as a security issue?

**Comment by brockallen** [comment]
> Thanks again for your quick reply! We definitely want to have the post-logout redirect URL validated with the pre-registered URLs. The problem right now is just that this only happens if we also specify an id_token.

The id token, in essence, authenticates the request to signout. That's the purpose.

**Comment by leastprivilege** [comment]
OK - we added a feature on dev that you get access to the raw parameters that were sent to the end_session endpoint (even when the call is not authenticated by an id token hint).

Will appear in RTM and our nightlies.

**Comment by cwe1ss** [comment]
Thank you Dominick! Will you validate the redirect_uri against all existing Uris or do we have to do it ourselves?

**Comment by brockallen** [comment]
You will have to do the validation yourself -- we didn't want to add new APIs to our store interfaces to model this one use case.

**Comment by cwe1ss** [comment]
Fair enough! Thanks Brock!!!
