### ISSUE TITLE
Protecting wcf service with IdentityServer4 openid connect protocol

### ISSUE THREAD

**Issue by ShubhraBakshi** [IdentityServer/IdentityServer4#561]
Hi, Can you provide a sample code for protecting my existing wcf services using openId connect.

I'm able to get the .aspx page protected using these lines of code

 if (!User.Identity.IsAuthenticated) 
            {
                HttpContext.Current.GetOwinContext().Authentication.Challenge(
                new AuthenticationProperties { RedirectUri = "http://localhost:1xx/" },
                OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
            else
            {
                if (((System.Security.Claims.ClaimsPrincipal)User).Claims != null)
                {
                    userName = User.Identity.Name;
                }
            }

But this is page level code. How can we do the redirect to authorization server from web.config file, so that all the aspx pages and services(using .svc hosted on IIS) hosted on that port will pass through the authentication.

**Comment by brockallen** [comment]
We had a sample here: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/WcfService

**Comment by cosmoKenney** [comment]
@brockallen I just looked into the WcfService project in the samples. That WCF service is self hosted (.exe). 
I'm running a WCF service hosted in my iis site (.asmx). It's part of my IDS4 web forms client site.
Since my asp.net site is already setup and pretty much working as a IDS4 client, do I even need to do any configuration (on the OP or Client) to protect the service?
