### ISSUE TITLE
Docs - ApiResource Scoped Client Confusion

### ISSUE THREAD

**Issue by stewart-noll-q2** [IdentityServer/IdentityServer4#589]
In the [docs](https://identityserver4.readthedocs.io/en/release/configuration/resources.html), two `ApiResource`'s are configured:

```csharp
public static IEnumerable<ApiResource> GetApis()
{
    return new[]
    {
        new ApiResource("api1", "Some API 1"),

        new ApiResource
        {
            Name = "api2",

            ...

            Scopes =
            {
                new Scope()
                {
                    Name = "api2.full_access",
                    DisplayName = "Full access to API 2",
                },
                new Scope
                {
                    Name = "api2.read_only",
                    DisplayName = "Read only access to API 2"
                }
            }
        }
    };
}
```
*note: since the overloaded constructor isn't being used to set the `Name` of the `ApiResource` like in api1,  api2 is not a scope of itself*

And on the next page a client is configured:

```csharp
var jsClient = new Client
{
    ClientId = "js",
    ...
    AllowedGrantTypes = GrantTypes.Implicit,
    ...
    AllowedScopes =
    {
        ...

        "api1", "api2"
    }
};
```

Looking through the source for identityserver4, it's not apparant where the relationship between the `Name` of the `ApiResource` and  the `AllowedScopes` of the `Client` cross paths, other than the note mentioned above.

Initially when I looked at the examples I assumed that the jsClient, by virtue of being scoped to api2, would be able to issue identity tokens scoped with api2.full_access and/or api2.read_only but now I'm a little confused.  Is this just a typo in the docs and the jsClient should explicitly be setting api2.full_access and/or api2.read_only or is there something else I'm missing?

Thanks for your time.

**Comment by leastprivilege** [comment]
I agree this is confusing. Will fix it. 

---
cheers
Dominick Baier




On Thu, Dec 15, 2016 at 2:07 AM +0100, "Stewart Noll" <notifications@github.com> wrote:












In the docs, two ApiResource's are configured:
public static IEnumerable<ApiResource> GetApis()
{
    return new[]
    {
        new ApiResource("api1", "Some API 1"),

        new ApiResource
        {
            Name = "api2",

            ...

            Scopes =
            {
                new Scope()
                {
                    Name = "api2.full_access",
                    DisplayName = "Full access to API 2",
                },
                new Scope
                {
                    Name = "api2.read_only",
                    DisplayName = "Read only access to API 2"
                }
            }
        }
    };
}


note: since the overloaded constructor isn't being used to set the Name of the ApiResource like in api1,  api2 is not a scope of itself


And on the next page a client is configured:
var jsClient = new Client
{
    ClientId = "js",
    ...
    AllowedGrantTypes = GrantTypes.Implicit,
    ...
    AllowedScopes =
    {
        ...

        "api1", "api2"
    }
};


Looking through the source for identityserver4, it's not apparant where the relationship between the Name of the ApiResource and  the AllowedScopes of the Client cross paths, other than the note mentioned above.


Initially when I looked at the examples I assumed that the jsClient, by virtue of being scoped to api2, would be able to issue identity tokens scoped with api2.full_access and/or api2.read_only but now I'm a little confused.  Is this just a typo in the docs and the jsClient should explicitly be setting api2.full_access and/or api2.read_only or is there something else I'm missing?


Thanks for your time.

**Comment by leastprivilege** [comment]
done on dev
