### ISSUE TITLE
User friendly error message when IdentityServer is not responding

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4#653]
I have both IdentityServer and WebApi as separate projects, I have configured the IdentityServer in the WebApi's Startup. If I run both IdentityServer and WebApi everything works fine, but When the IdentityServer is not running and I run the WebApi Project, I get the yellow screen with exception that 
> connection could not be established to localhost:5000

what I want is that instead of this yellow page i should get an error message as a JSON response , 

I have tried to place a middleware just before the IdentityServer's middleware to catch any unhandled exception but It doesn't work. 

Kindly share any solution if you have ..

**Comment by brockallen** [comment]
That's a connection error from the Microsoft JWT validation middleware that we wrap. It happens when the API layer needs to load the metadata to validate tokens. You'd have to contact Microsoft to find out a way to handle that exception. I don't have their code in front of me to debug where the exception is thrown.
