### ISSUE TITLE
user store

### ISSUE THREAD

**Issue by JanickRoss** [IdentityServer/IdentityServer4#800]
The best way to store users information is aspnet identity or you recommand to use an other way for user persistence ?

If I want add customs fields on registration form, do you have an example or tutorial ?

**Comment by TomCJones** [comment]
The ASP.NET sample shows one way to store user information. It is based on the user identity being a single login credential, either some variant of openIDconnect or a local store. There is no other way that I know for ASP.NET to store identity information. I am rewriting that sample to include both a user-centric user store (rather than email-centric as it is today) and to enable dynamic registration, which is the biggest change for ASP.NET.  I was hoping to move this sample to GitHub and relate it to the other efforts on this site. Who would be interested in that effort and who could help me get a project set up on GitHub?

**Comment by brockallen** [comment]
ASP.NET Identity is designed for managing the data related to authentication of users (passwords, email for password reset, phone for 2fa, etc). "Business data" for users should just be regular data in your app, but key'd using the `sub` claim that you get back from authenticating in IdentityServer. The `sub` claim comes from the `UserId` property when using ASP.NET Identity.

**Comment by JanickRoss** [comment]
If I want to ask for the city during the registration process, and I would like to receive it in my "claims", you advise me where to place them?

**Comment by brockallen** [comment]
In your registration UI, and then configure IS according to the docs to issue specific claim types.
