### ISSUE TITLE
User denying consent isn't an "error"

### ISSUE THREAD

**Issue by ChrisSimmons** [IdentityServer/IdentityServer4#815]
I notice that the user not giving consent [causes an error](https://github.com/IdentityServer/IdentityServer4/blob/9ca4193c9876b8b1831093e4fe68506205ad9fe3/src/IdentityServer4/ResponseHandling/AuthorizeInteractionResponseGenerator.cs#L222).  On the face of it, this doesn't seem unreasonable, but this then causes an ERROR-level log (via [this](https://github.com/IdentityServer/IdentityServer4/blob/e49e8f204812867a0d19d4d8bc51b6a067b01705/src/IdentityServer4/Endpoints/AuthorizeEndpoint.cs#L194) and finally [this](https://github.com/IdentityServer/IdentityServer4/blob/e49e8f204812867a0d19d4d8bc51b6a067b01705/src/IdentityServer4/Endpoints/AuthorizeEndpoint.cs#L235)).  To me, an error in the logs tells me something went wrong in the code: an application problem that needs attention.  A user not consenting to the requested grants, while exceptional, is still a valid course of action in the application.  At _worst_, this should only be a WARN-level log although if I were king, it'd only be INFO.

Am I alone on this?

**Comment by leastprivilege** [comment]
valid point - @brockallen will look into it.

**Comment by MHHenriksen** [comment]
The same goes for many of the other results in the AuthorizeInteractionResponseGenerator, like [prompt=none was requested but user is not authenticated](https://github.com/IdentityServer/IdentityServer4/blob/9ca4193c9876b8b1831093e4fe68506205ad9fe3/src/IdentityServer4/ResponseHandling/AuthorizeInteractionResponseGenerator.cs#L98) (mentioning this one in particular because it was brought up during internal testing).

**Comment by brockallen** [comment]
Ok, I added a flag to suppress the error written to the log when there's an protocol error response due to interaction.
