### ISSUE TITLE
how to custom define token store and token validate

### ISSUE THREAD

**Issue by bachsyl** [IdentityServer/IdentityServer4#818]
hello

i want ask how to custom define token store and token validate, i mean if there exist large number of user token need to store and validate, maybe store in redis ,but how to define it or overwrite?

**Comment by joshpearce** [comment]
The default stores are defined [here](https://github.com/IdentityServer/IdentityServer4/tree/dev/src/IdentityServer4/Stores/Default). So that should be a good start for defining your own.

I do not recommend using Redis for persistence. That is because the query patterns in the store interfaces will cause you to do full scans in Redis or to implement some lookup table in another Redis key, and we found that code to be error-prone. In my opinion, it's best to use SQL as it matches the usage pattern.

Once you define your new stores, you wire them up in Startup.cs, in the ConfigureServices method, using services an instance of IServiceCollection. That is your IoC container provided by the ASP.NET Core framework.

Assuming you write your repositories to be thread safe, try adding then as Singleton scope. Like this:

`services.AddSingleton<IClientStore, MyClientStore>();`
