### ISSUE TITLE
AddSigningCredential rsa security key method

### ISSUE THREAD

**Issue by anirudhharidas** [IdentityServer/IdentityServer4#949]
Can you please help me to generate and set rsa security key for signing the credentials

**Comment by vdecristofaro** [comment]
https://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/

**Comment by leastprivilege** [comment]
Generally X509 certs and the cert store are more recommended because lifetime and storage is taken care of.

We have some helpers in the upcoming 1.4 that makes it easier to create raw RSA keys though.

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs#L137
