### ISSUE TITLE
Identity Server 4 .net core only ?

### ISSUE THREAD

**Issue by oferAshkenazy** [IdentityServer/IdentityServer4#97]
I seems that the project IdentityServer4 & IdentityServer4.AccessTokenValidation projects
are ".Net core" only as a result i can't add any of my own .net 4.6.1 assemblies ?

**Comment by totht91** [comment]
Can you try with 4.6.2?

**Comment by brockallen** [comment]
I think we're targeting netstandard1.5 right now. We'll evaluate this and pick the lowest one possible.

**Comment by bburman** [comment]
My eyes may be deceiving me, but it looks as if netcoreapp1.0 slid to netstandard1.6 over the weekend:

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by BurningEnlightenment** [comment]
> My eyes may be deceiving me, but it looks as if netcoreapp1.0 slid to netstandard1.6 over the weekend

@bburman So what? This just means that some new APIs became consumable by .net core apps. Because this class library targets netstandard 1.5 you can use it from any project targeting netstandard 1.5 or *higher* (obviously including netcoreapp 1.0), so nothing really changed from this project's perspective :wink:

**Comment by tillig** [comment]
It'd be nice to see an update to a lower required framework version sooner rather than later if possible (e.g., pre RC3). Even if your app targets `net46` that doesn't work with `netstandard1.5` and .NET 4.6.2 is still only in preview. I know we're riding the bleeding edge, but... that's a little too bleeding for me. In the meantime I've basically had to fork everything IdentityServer/IdentityModel and publish internal versions that support .NET 4.6.

**Comment by leastprivilege** [comment]
gonna look into that next week.

**Comment by leastprivilege** [comment]
i updated all the packages - give it a go and see if that works better for you (and open a new issue if you encounter problems)
